### ISSUE TITLE
[BUG] downloadonly option fails as tries to generate hdf5 model file

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#165]
**Describe the bug**
downloadonly option fails as tries to generate hdf5 model file
Being addressed under #163 

```
2020-10-29 07:09:43,214 INFO Download rate 4.3M/s                                                                                                                                                                
/Users/dbekaert/Software/python/miniconda37/envs/RAIDER/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cds.climate.copernicus.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
WARNING: download_only flag selected. No further processing will happen.
2020-10-29 07:09:43,881 WARNING download_only flag selected. No further processing will happen.
ERROR: Unable to save weathermodel to file
Traceback (most recent call last):
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAIDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/delay.py", line 135, in tropo_delay
    weather_model.write2HDF5(weather_model_file)
AttributeError: 'NoneType' object has no attribute 'write2HDF5'
2020-10-29 07:09:43,882 ERROR Unable to save weathermodel to file
Traceback (most recent call last):
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAIDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/delay.py", line 135, in tropo_delay
    weather_model.write2HDF5(weather_model_file)
AttributeError: 'NoneType' object has no attribute 'write2HDF5'
```

**Comment by dbekaert** [comment]
adressed via #163
