### ISSUE TITLE
[BUG] incorrect use netcdf versus hdf5 for GMAO in download-only; and h5py not defined error

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#188]
When using the --downoad_only mode, GMAO download stores file with a netcdf extension.
When running without it stores the GMAO file wih hdf5 extension.

```
(RAiDER-download) [dbekaert@leffe weather_files]$ raiderDelay.py --time 18:00 --model GMAO --date 20191223 --bbox -90 90 -180 180 -v --download_only
2020-11-06 23:23:24,253 DEBUG Starting to run the weather model calculation
2020-11-06 23:23:24,253 DEBUG Time type: <class 'datetime.datetime'>
2020-11-06 23:23:24,254 DEBUG Time: 20191223
2020-11-06 23:23:24,254 DEBUG Flag type is bounding_box
2020-11-06 23:23:24,254 DEBUG DEM/height type is "skip"
2020-11-06 23:23:24,254 DEBUG Beginning weather model pre-processing
2020-11-06 23:23:24,254 DEBUG Download-only is True
2020-11-06 23:23:24,255 DEBUG Storing weather model at: ./weather_files/GMAO_2019_12_23_T18_00_00.nc
Weather model GMAO is available from 2017-12-01 00:00:00-Present
2020-11-06 23:23:24,255 INFO Weather model GMAO is available from 2017-12-01 00:00:00-Present
2020-11-06 23:23:27,658 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?qv.qv[6022:1:6022][0:1:71][0:1:720][0:1:1151]
2020-11-06 23:23:58,229 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?pl.pl[6022:1:6022][0:1:71][0:1:720][0:1:1151]
2020-11-06 23:24:26,240 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?t.t[6022:1:6022][0:1:71][0:1:720][0:1:1151]
2020-11-06 23:24:50,192 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?h.h[6022:1:6022][0:1:71][0:1:720][0:1:1151]
WARNING: download_only flag selected. No further processing will happen.
2020-11-06 23:25:15,655 WARNING download_only flag selected. No further processing will happen.
```

But if you re-run it errors out:
```
2020-11-06 23:26:16,173 DEBUG Time: 20191223
2020-11-06 23:26:16,173 DEBUG Flag type is bounding_box
2020-11-06 23:26:16,173 DEBUG DEM/height type is "skip"
2020-11-06 23:26:16,173 DEBUG Beginning weather model pre-processing
2020-11-06 23:26:16,173 DEBUG Download-only is True
2020-11-06 23:26:16,173 DEBUG Storing weather model at: ./weather_files/GMAO_2019_12_23_T18_00_00.nc
2020-11-06 23:26:16,173 WARNING Weather model already exists, skipping download
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 215, in _tropo_delay
    (_, _) = tropo_delay(*chunk_params)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 148, in tropo_delay
    time=time, download_only=download_only, makePlots=True
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/processWM.py", line 93, in prepareWeatherModel
    weather_model.load(*weather_model.files, outLats=lats, outLons=lons, los=los, zref=zref)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 165, in load
    self.load_weather(*args, **kwargs)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/gmao.py", line 124, in load_weather
    self._load_model_level(f)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/gmao.py", line 132, in _load_model_level
    with h5py.File(filename, 'r') as f:
NameError: name 'h5py' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-download/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 184, in parseCMD
    pool.map(_tropo_delay, lst_new_args)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
NameError: name 'h5py' is not defined
```

If you do not us multi-pool then its becomes clear that the filename is now an h5 file, and also errors out for the same reason.

versus:
```
(RAiDER-download) [dbekaert@leffe weather_files]$ raiderDelay.py --time 18:00 --model GMAO --date 20191223 --bbox -90 90 -180 180 -v 
2020-11-06 23:27:17,986 DEBUG Starting to run the weather model calculation
2020-11-06 23:27:17,986 DEBUG Time type: <class 'datetime.datetime'>
2020-11-06 23:27:17,986 DEBUG Time: 20191223
2020-11-06 23:27:17,986 DEBUG Flag type is bounding_box
2020-11-06 23:27:17,986 DEBUG DEM/height type is "skip"
2020-11-06 23:27:17,986 DEBUG Beginning weather model pre-processing
2020-11-06 23:27:17,986 DEBUG Download-only is False
2020-11-06 23:27:17,987 DEBUG Storing weather model at: ./weather_files/GMAO_2019_12_23_T18_00_00.h5
Weather model GMAO is available from 2017-12-01 00:00:00-Present
2020-11-06 23:27:17,987 INFO Weather model GMAO is available from 2017-12-01 00:00:00-Present
2020-11-06 23:27:21,155 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?qv.qv[6022:1:6022][0:1:71][0:1:720][0:1:1151]
2020-11-06 23:27:41,978 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?pl.pl[6022:1:6022][0:1:71][0:1:720][0:1:1151]
2020-11-06 23:28:02,793 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?t.t[6022:1:6022][0:1:71][0:1:720][0:1:1151]
2020-11-06 23:28:22,608 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?h.h[6022:1:6022][0:1:71][0:1:720][0:1:1151]
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-download/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 197, in parseCMD
    outformat, t, out, download_only, wfn, hfn)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 148, in tropo_delay
    time=time, download_only=download_only, makePlots=True
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/processWM.py", line 93, in prepareWeatherModel
    weather_model.load(*weather_model.files, outLats=lats, outLons=lons, los=los, zref=zref)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 165, in load
    self.load_weather(*args, **kwargs)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/gmao.py", line 124, in load_weather
    self._load_model_level(f)
  File "/home/dbekaert/python/python36/envs/RAiDER-download/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/gmao.py", line 132, in _load_model_level
    with h5py.File(filename, 'r') as f:
NameError: name 'h5py' is not defined
```

**Comment by dbekaert** [comment]
fixed through #192
