### ISSUE TITLE
[BUG] HRES dtype error when loading the global data (Memory?)

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#195]
**Describe the bug**

HRES delay code errors out when trying to load the global file. Might be memory related (https://stackoverflow.com/questions/55024259/valueerror-when-changing-to-a-larger-dtype-its-size-must-be-a-divisor-of-the-t)

```
(RAiDER-HRES-station) [dbekaert@leffe HRES]$ raiderDelay.py --time 06:00 --model HRES --date 20090101 --station_file ../GNSS/gnssStationList_overbbox.csv --zref 30000 -v
2020-11-07 20:09:11,180 DEBUG Starting to run the weather model calculation
2020-11-07 20:09:11,180 DEBUG Time type: <class 'datetime.datetime'>
2020-11-07 20:09:11,180 DEBUG Time: 20090101
2020-11-07 20:09:11,180 DEBUG Flag type is station_file
2020-11-07 20:09:11,181 DEBUG DEM/height type is "pandas"
2020-11-07 20:09:11,181 DEBUG Beginning weather model pre-processing
2020-11-07 20:09:11,181 DEBUG Download-only is False
2020-11-07 20:09:11,181 DEBUG Storing weather model at: ./weather_files/HRES_2009_01_01_T06_00_00.nc
WARNING: Weather model already exists, skipping download
2020-11-07 20:09:11,181 WARNING Weather model already exists, skipping download
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 178, in parseCMD
    _tropo_delay(args)
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 189, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 151, in tropo_delay
    time=time, download_only=download_only, makePlots=True
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/processWM.py", line 93, in prepareWeatherModel
    weather_model.load(*weather_model.files, outLats=lats, outLons=lons, los=los, zref=zref)
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 165, in load
    self.load_weather(*args, **kwargs)
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/hres.py", line 139, in load_weather
    lats, lons, xs, ys, t, q, lnsp, z = self._makeDataCubes(filename, verbose=False)
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/hres.py", line 220, in _makeDataCubes
    with nc.netcdf_file(fname, 'r', maskandscale=True) as f:
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/scipy/io/netcdf.py", line 281, in __init__
    self._read()
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/scipy/io/netcdf.py", line 610, in _read
    self._read_var_array()
  File "/home/dbekaert/python/python36/envs/RAiDER-HRES-station/lib/python3.7/site-packages/scipy/io/netcdf.py", line 716, in _read_var_array
    rec_array = self._mm_buf[begin:begin+self._recs*self._recsize].view(dtype=dtypes)
ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype
```

**Comment by jlmaurer** [comment]
This was fixed in #234 I believe.
