### ISSUE TITLE
GMAO model bounds constraint for historic data

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#199]
@leiyangleon @bbuzz31 could you have a look at the bounds being reported out of the historic versus current day GMAO.

Perhaps @bbuzz31 you could compare for an overlapping day the reported lonlat.
Goes back to an earlier issue ticket of reporting pixel center, top-left corner of observation.
I also believe @leiyangleon made some internal fixes for other models?

## Historic GMAO

The command to replicate:
```
raiderDelay.py --time 06:00 --model GMAO --date 20171001 20171230 12  --bbox -90 90 -180 180 -v
```
The output
```
(RAiDER-gmao) [dbekaert@leffe weather_files]$ raiderDelay.py --time 06:00 --model GMAO --date 20171001 20171230 12  --bbox -90 90 -180 180 -v
2020-11-10 20:58:26,714 DEBUG Starting to run the weather model calculation
2020-11-10 20:58:26,714 DEBUG Time type: <class 'datetime.datetime'>
2020-11-10 20:58:26,715 DEBUG Time: 20171001  
2020-11-10 20:58:26,715 DEBUG Flag type is bounding_box
2020-11-10 20:58:26,715 DEBUG DEM/height type is "skip"
2020-11-10 20:58:26,715 DEBUG Beginning weather model pre-processing
2020-11-10 20:58:26,715 DEBUG Download-only is False
2020-11-10 20:58:26,715 DEBUG Storing weather model at: ./weather_files/GMAO_2017_10_01_T06_00_00.nc
WARNING: Weather model already exists, skipping download
2020-11-10 20:58:26,715 WARNING Weather model already exists, skipping download
Extent of the input lats/lons is: [-90.0, 90.0, -180.0, 180.0]
2020-11-10 21:00:26,303 INFO Extent of the input lats/lons is: [-90.0, 90.0, -180.0, 180.0]
Extent of the weather model is: [-90.0, 90.0, -180.0, 179.6875]
2020-11-10 21:00:26,304 INFO Extent of the weather model is: [-90.0, 90.0, -180.0, 179.6875]
The weather model passed does not cover all of the input points; you need to download a larger area.
2020-11-10 21:00:26,304 INFO The weather model passed does not cover all of the input points; you need to download a larger area.
ERROR: Date 2017-10-01 06:00:00 failed
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-gmao/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 198, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/home/dbekaert/python/python36/envs/RAiDER-gmao/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 151, in tropo_delay
    time=time, download_only=download_only, makePlots=True
  File "/home/dbekaert/python/python36/envs/RAiDER-gmao/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/processWM.py", line 96, in prepareWeatherModel
    weather_model.load(*weather_model.files, outLats=lats, outLons=lons, los=los, zref=zref)
  File "/home/dbekaert/python/python36/envs/RAiDER-gmao/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 172, in load
    self._adjust_grid(lats=outLats, lons=outLons)
  File "/home/dbekaert/python/python36/envs/RAiDER-gmao/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 318, in _adjust_grid
    raise RuntimeError('Check the weather model')
RuntimeError: Check the weather model
2020-11-10 21:00:26,304 ERROR Date 2017-10-01 06:00:00 failed
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-gmao/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 198, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/home/dbekaert/python/python36/envs/RAiDER-gmao/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 151, in tropo_delay
    time=time, download_only=download_only, makePlots=True
  File "/home/dbekaert/python/python36/envs/RAiDER-gmao/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/processWM.py", line 96, in prepareWeatherModel
    weather_model.load(*weather_model.files, outLats=lats, outLons=lons, los=los, zref=zref)
  File "/home/dbekaert/python/python36/envs/RAiDER-gmao/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 172, in load
    self._adjust_grid(lats=outLats, lons=outLons)
  File "/home/dbekaert/python/python36/envs/RAiDER-gmao/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 318, in _adjust_grid
    raise RuntimeError('Check the weather model')

```

## Current Day GMAO
The command works fine. To replicate:
```
raiderDelay.py --time 06:00 --model GMAO --date 20171230 --bbox -90 90 -180 180 -v
```

Full output
```
(RAiDER-gmao) [dbekaert@leffe weather_files]$ raiderDelay.py --time 06:00 --model GMAO --date 20171230 --bbox -90 90 -180 180 -v
2020-11-10 21:07:51,911 DEBUG Starting to run the weather model calculation
2020-11-10 21:07:51,911 DEBUG Time type: <class 'datetime.datetime'>
2020-11-10 21:07:51,912 DEBUG Time: 20171230  
2020-11-10 21:07:51,912 DEBUG Flag type is bounding_box
2020-11-10 21:07:51,912 DEBUG DEM/height type is "skip"
2020-11-10 21:07:51,912 DEBUG Beginning weather model pre-processing
2020-11-10 21:07:51,912 DEBUG Download-only is False
2020-11-10 21:07:51,912 DEBUG Storing weather model at: ./weather_files/GMAO_2017_12_30_T06_00_00.h5
Weather model GMAO is available from 2014-02-20 00:00:00-Present
2020-11-10 21:07:51,912 INFO Weather model GMAO is available from 2014-02-20 00:00:00-Present
2020-11-10 21:07:55,563 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?qv.qv[234:1:234][0:1:71][0:1:720][0:1:1151]
2020-11-10 21:08:18,345 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?pl.pl[234:1:234][0:1:71][0:1:720][0:1:1151]
2020-11-10 21:08:37,828 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?t.t[234:1:234][0:1:71][0:1:720][0:1:1151]
2020-11-10 21:09:02,901 INFO Fetching URL: https://opendap.nccs.nasa.gov/dods/GEOS-5/fp/0.25_deg/assim/inst3_3d_asm_Nv.dods?h.h[234:1:234][0:1:71][0:1:720][0:1:1151]
2020-11-10 21:13:03,228 DEBUG Number of weather model nodes: 60223686
2020-11-10 21:13:03,229 DEBUG Shape of weather model: (718, 1149, 73)
2020-11-10 21:13:03,230 DEBUG Bounds of the weather model: -89.75/89.50/-179.69/179.06 (SNWE)
2020-11-10 21:13:03,230 DEBUG Weather model: GMAO
2020-11-10 21:13:03,780 DEBUG Mean value of the wet refractivity: 7.821810
2020-11-10 21:13:04,332 DEBUG Mean value of the hydrostatic refractivity: 89.508995
2020-11-10 21:13:04,332 DEBUG 
======Weather Model class object=====
Number of points in Lon/Lat = 718/1149
Total number of grid points (3D): 60223686
Latitude resolution: 0.25
Longitude resolution: 0.3125
Native projection: epsg:4326
ZMIN: -100.0
ZMAX: 15000.0
Minimum/Maximum y: -89.75/ 89.50
Minimum/Maximum x: -179.69/ 179.06
Minimum/Maximum zs/heights:    -100.00/  76741.68
=====================================
k1 = 0.776
k2 = 0.233
k3 = 3750.0
Humidity type = q
=====================================
Class name: gmao
Dataset: gmao
=====================================
A: []
B: []

2020-11-10 21:13:16,559 DEBUG Beginning DEM calculation
2020-11-10 21:13:16,559 DEBUG Beginning delay calculation
2020-11-10 21:13:16,559 DEBUG Reference z-value (max z for integration) is . m
2020-11-10 21:13:16,559 DEBUG Number of processors to use: 1
Delays have been written to the weather model file; see ./weather_files/GMAO_2017-12-30T06_00_00_90.0S_90.0N_180.0W_180.0E.h5
2020-11-10 21:13:25,705 INFO Delays have been written to the weather model file; see ./weather_files/GMAO_2017-12-30T06_00_00_90.0S_90.0N_180.0W_180.0E.h5

```

**Comment by leiyangleon** [comment]
@bbuzz31 @dbekaert Yes, I fixed the bounds internally for all models. GMAO and MERRA-2 need to be taken care of particularly. See these [lines](https://github.com/dbekaert/RAiDER/blob/730562cd01545e1c9fc6f738566f54e586903137/tools/RAiDER/models/weatherModel.py#L132-L156). When you modify that function, please also change "is" to "==" in the if statements.

**Comment by bbuzz31** [comment]
@dbekaert you are on the dev branch I assume? I get different messages and no statements on the dl_historic_gmao branch

**Comment by bbuzz31** [comment]
I've tested on the dev branch now with still no issues. I get the following messages (note the bounds, and debug vs info in logger)
```
2020-11-11 14:01:51,548 INFO Fetching URL: https://portal.nccs.nasa.gov/datashare/gmao/geos-fp/das/Y2017/M10/D01/GEOS.fp.asm.inst3_3d_asm_Nv.20171001_0600.V01.nc4
2020-11-11 14:08:24,343 DEBUG Number of weather model nodes: 60223686
2020-11-11 14:08:24,343 DEBUG Shape of weather model: (718, 1149, 73)
2020-11-11 14:08:24,344 DEBUG Bounds of the weather model: -89.75/89.50/-179.69/179.06 (SNWE)

**Comment by dbekaert** [comment]
@bbuzz31 weird. It might have been related to my old build folder.
I reran it and now it passes:

```
raiderDelay.py --time 06:00 --model GMAO --date 20171001 20171230 12  --bbox -90 90 -180 180 -v
2020-11-11 12:08:58,472 DEBUG Starting to run the weather model calculation
2020-11-11 12:08:58,472 DEBUG Time type: <class 'datetime.datetime'>
2020-11-11 12:08:58,473 DEBUG Time: 20171001
2020-11-11 12:08:58,473 DEBUG Flag type is bounding_box
2020-11-11 12:08:58,473 DEBUG DEM/height type is "skip"
2020-11-11 12:08:58,473 DEBUG Beginning weather model pre-processing
2020-11-11 12:08:58,473 DEBUG Download-only is False
2020-11-11 12:08:58,473 DEBUG Storing weather model at: ./weather_files/GMAO_2017_10_01_T06_00_00.nc
Weather model GMAO is available from 2014-02-20 00:00:00-Present
2020-11-11 12:08:58,473 INFO Weather model GMAO is available from 2014-02-20 00:00:00-Present
Fetching URL: https://portal.nccs.nasa.gov/datashare/gmao/geos-fp/das/Y2017/M10/D01/GEOS.fp.asm.inst3_3d_asm_Nv.20171001_0600.V01.nc4
2020-11-11 12:08:58,473 INFO Fetching URL: https://portal.nccs.nasa.gov/datashare/gmao/geos-fp/das/Y2017/M10/D01/GEOS.fp.asm.inst3_3d_asm_Nv.20171001_0600.V01.nc4
2020-11-11 12:12:43,359 DEBUG Number of weather model nodes: 60223686
2020-11-11 12:12:43,361 DEBUG Shape of weather model: (718, 1149, 73)
2020-11-11 12:12:43,361 DEBUG Bounds of the weather model: -89.75/89.50/-179.69/179.06 (SNWE)
2020-11-11 12:12:43,361 DEBUG Weather model: GMAO
2020-11-11 12:12:43,899 DEBUG Mean value of the wet refractivity: 8.609937
2020-11-11 12:12:44,523 DEBUG Mean value of the hydrostatic refractivity: 89.074652
2020-11-11 12:12:44,523 DEBUG 
======Weather Model class object=====

```
