### ISSUE TITLE
Multi-procesing for delays fails

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#207]
Capturing this here to be addressed in future:

to replicate:
```
raiderDelay.py --time 18:00 --model ERA5 --date 20090101 20191231 12 --station_file ../GNSS/gnssStationList_overbbox.csv --zref 30000 -v --parallel 10
```

Outputs:
```

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-stats/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-stats/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-stats/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-stats/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-stats/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 175, in parseCMD
    pool.map(_tropo_delay, lst_new_args)
  File "/home/dbekaert/python/python36/envs/RAiDER-stats/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/dbekaert/python/python36/envs/RAiDER-stats/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError: daemonic processes are not allowed to have children
```

**Comment by jlmaurer** [comment]
This was closed by #230
