### ISSUE TITLE
HRES failure due to a/b level update not done upon re-run

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#241]
We had this fixed before; looks like a revert creeped into the code.

```
(RAiDER-NISAR-ST) [dbekaert@leffe HRES]$ raiderDelay.py --time 06:00 --model HRES --date 20090101 --station_file ../GNSS/partial_stations/gnssStationList_overbbox_A_Lon-180to-90.csv --zref 30000 -v
WARNING: Weather model already exists, please remove it ("['./weather_files/HRES_2009_01_01_T06_00_00.nc']") if you want to download a new one.
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 193, in parseCMD
    _tropo_delay(new_args)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 205, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 120, in tropo_delay
    makePlots = True
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/processWM.py", line 80, in prepareWeatherModel
    zref = zref,
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 189, in load
    self.load_weather(*args, **kwargs)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/hres.py", line 168, in load_weather
    geo_hgt, pres, hgt = self._calculategeoh(z, lnsp)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 480, in _calculategeoh
    'course, these three numbers should be equal.')
ValueError: I have here a model with 91 levels, but parameters a and b have lengths 138 and 138 respectively. Of course, these three numbers should be equal.
```

**Comment by dbekaert** [comment]
Do not think that the levels should be set when downloading the model.
https://github.com/dbekaert/RAiDER/blob/78771728c4dc7888a3f7dc3338be273a58e95182/tools/RAiDER/models/hres.py#L263

Suspect that this part of the code will get skipped if the model already has been downloaded.
Better practice would be to set the model level in the load step.
Would suggest here: https://github.com/dbekaert/RAiDER/blob/78771728c4dc7888a3f7dc3338be273a58e95182/tools/RAiDER/models/hres.py#L140

@jlmaurer thoughts?

**Comment by dbekaert** [comment]
this has been fixed under PR #243

**Comment by dbekaert** [comment]
@jlmaurer bug has been introduced while fixing for the historic data.
Can you correct it and add unittests for both historic and current day? see #247 


```
Finished writing data to ./HRES_Delay_20130528T060000_Zmax30000.0.csv
WARNING: Weather model already exists, please remove it ("['./weather_files/HRES_2013_08_20_T06_00_00.nc']") if you want to download a new one.
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 198, in parseCMD
    _tropo_delay(new_args)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 219, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 120, in tropo_delay
    makePlots=True
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/processWM.py", line 80, in prepareWeatherModel
    zref=zref,
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 200, in load
    self.load_weather(*args, **kwargs)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/hres.py", line 170, in load_weather
    geo_hgt, pres, hgt = self._calculategeoh(z, lnsp)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 499, in _calculategeoh
    'course, these three numbers should be equal.')
ValueError: I have here a model with 137 levels, but parameters a and b have lengths 92 and 92 respectively. Of course, these three numbers should be equal.
```

**Comment by dbekaert** [comment]
This might have been driver error. I tried again and it seems to work.
Likely i launched the jobs and re-compiled the code later on again with the fix.

Will check again and let you know if this is really an issue or not.

**Comment by jlmaurer** [comment]
ok @dbekaert keep me posted. I'll work on some unit tests to try to eliminate these kinds of bugs creeping in as well.

**Comment by dbekaert** [comment]
Seems to work for now but i cannot run as many in parallel. Works for historic HRES but then the new once has 137 instead of the 87 levels or so.

The error is memory related so this makes me wonder if we really need float64 or not.
Could we make it all work with float32?

Suggest we plan for a sensitivity test to asses it

```
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 198, in parseCMD
    _tropo_delay(new_args)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 219, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 120, in tropo_delay
    makePlots=True
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/processWM.py", line 80, in prepareWeatherModel
    zref=zref,
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 212, in load
    self._getZTD(zref)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 372, in _getZTD
    hydro[..., level:], x=self._zs[level:], axis=2
  File "<__array_function__ internals>", line 6, in trapz
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4163, in trapz
    ret = (d * (y[tuple(slice1)] + y[tuple(slice2)]) / 2.0).sum(axis)
numpy.core._exceptions.MemoryError: Unable to allocate 2.26 GiB for an array with shape (2033, 1090, 137) and data type float64
```

**Comment by dbekaert** [comment]
issue is resolved will make seperate issue ticket for the float64 part.
