### ISSUE TITLE
HRES failure in computeDelay related to parallel chunking

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#242]
With the chunking of quadrant i am able to run the HRES Raider code.

command used:
```
raiderDelay.py --time 06:00 --model HRES --date 20130703  --station_file ../GNSS/partial_stations/gnssStationList_overbbox_A_Lon-180to-90.csv --z
ref 30000 -v
```

Experiencing an error for writing file:

```
(RAiDER-NISAR-ST) [dbekaert@leffe HRES]$ raiderDelay.py --time 06:00 --model HRES --date 20130703  --station_file ../GNSS/partial_stations/gnssStationList_overbbox_A_Lon-180to-90.csv --z
ref 30000 -v
WARNING: Weather model already exists, please remove it ("['./weather_files/HRES_2013_07_03_T06_00_00.nc']") if you want to download a new one.

Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 193, in parseCMD
    _tropo_delay(new_args)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 205, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 165, in tropo_delay
    out = out,
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 68, in computeDelay
    weather_model_file_name,
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delayFcns.py", line 128, in get_delays
    individual_results = pool.starmap(process_chunk, chunk_inputs)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

**Comment by dbekaert** [comment]
Seems to be something going wrong in our chunking.It errors after 5 min or so.
Looks like there is too much overhead and the chunksize might not be set correctly?
Printing the number of chunks, the chunk size and size of dataset that yields the error:
```
49 = number of chunks
[124] = chunk size
[5964] = size
```

Manually hard-coding the chunksize to be the dataset size runs fine and within seconds.
```
1
[5964]
[5964]

```

**Comment by jlmaurer** [comment]
Dropping in [this webpage](https://stackoverflow.com/questions/47776486/python-struct-error-i-format-requires-2147483648-number-2147483647) with a similar issue.

**Comment by dbekaert** [comment]
this is all refactored now
