### ISSUE TITLE
memory need: Float64 versus Float32

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#251]
Issue ticket for us to assess what precision is really needed for the variables.
e.g. Lon lat should remain float64 for precision purposes at the 10m level.

Need to assess what is needed for the other variables separately:
- P
- T
- q
- e
- hydrostatic refractivity => gets carried in mem for the interpolation object
- wet refractivity => gets carried in mem for the interpolation object
- wet delay
- hydrostatic delay

Below is an example which shows for HRES that currently float64 is used:

```
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 198, in parseCMD
    _tropo_delay(new_args)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 219, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 120, in tropo_delay
    makePlots=True
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/processWM.py", line 80, in prepareWeatherModel
    zref=zref,
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 212, in load
    self._getZTD(zref)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 372, in _getZTD
    hydro[..., level:], x=self._zs[level:], axis=2
  File "<__array_function__ internals>", line 6, in trapz
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4163, in trapz
    ret = (d * (y[tuple(slice1)] + y[tuple(slice2)]) / 2.0).sum(axis)
numpy.core._exceptions.MemoryError: Unable to allocate 2.26 GiB for an array with shape (2033, 1090, 137) and data type float64
```

**Comment by dbekaert** [comment]
@jlmaurer @cmarshak:  But likely with x-array we would not be up-scaling it to Float64 given that the model variables are mostly  Float32. So perhaps with x-array this might solve itself. Still i think it would be good for us to be explicit in case new models are added with a precision which is too large for what is needed.

However for the intermediate solution suggest we make an intermediate fix for now.

It would also be good to understand where we could for example leverage a float16 instead of a float32.

**Comment by dbekaert** [comment]
An intermediate solution on our server it to overwrite the memory allocation protocol: https://stackoverflow.com/questions/57507832/unable-to-allocate-array-with-shape-and-data-type

**Comment by dbekaert** [comment]
@jlmaurer the memory issues are encountered before when computing the hydrostatic and wet delays.
So that would be in the model class itself. Changes in #253 are not at correct location to mitigate the issues.

Best to verify the precision changes before we make the change.
- Local coordinates in m are like good to be in float 32
- Coordinates in lon lat should stay in float64 as that map to m changes.
- Height i suspect will be fine in float32.

Wrt to the model variables
- the height is derived from the coordinates which is float64. at some point it should be able to convert that to float32. Likely not as part of the calculation. Hence we should do some tests here.
