### ISSUE TITLE
working Zenith, model node, DEM example

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#27]
# Scenario:
Example: Running ERA5 at weather model nodes at DEM height over BBoX

Code used:
```
raiderDelay.py --date 20190415 --time 1200  --model ERA5 --modelBBOX 36 -121 34 -119 
```

# Errors to be fixed:
1. re-run of hgt verus dem enabled
**Error:**  not very clear for a user to know what the issue is, and its caused by a user driver error:
**Solution:** By removing the "geom" folder the issue got removed.
<details>

```raiderDelay.py --date 20190415 --time 1200  --model ERA5 --modelBBOX 36 -121 34 -119 
Weather model already exists, please remove it ("weather_files/ERA5_2019-04-15 12:00:00.h5") if you want to create a new one.
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py:267: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  lengths = np.linalg.norm(f['LOS'].value, axis=-1)
Traceback (most recent call last):
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/bin/raiderDelay.py", line 13, in <module>
    parseCMD()
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/runProgram.py", line 146, in parseCMD
    (_,_) = tropo_delay(los, lats, lons, heights, flag, weather_model, wmLoc, zref,
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py", line 186, in tropo_delay
    computeDelay(weather_model_file, pnts_file, zref, out,
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py", line 111, in computeDelay
    wet, hydro = interpolateDelay(weather_model_file_name, pnts_file_name, zref = zref,
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py", line 69, in interpolateDelay
    RAiDER.delayFcns.calculate_rays(pnts_file_name, stepSize, verbose = verbose)
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py", line 288, in calculate_rays
    getUnitLVs(pnts_file) 
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py", line 250, in getUnitLVs
    get_lengths(pnts_file)
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py", line 273, in get_lengths
    f['Rays_len'][:] = lengths
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Rays_len' doesn't exist)"
```
</details>

2. undefined getIntFcn2 function
**Error:**  name 'getIntFcn2' is not defined
<details>

``` raiderDelay.py --date 20190415 --time 1200  --model ERA5 --modelBBOX 36 -121 34 -119 
Weather model already exists, please remove it ("weather_files/ERA5_2019-04-15 12:00:00.h5") if you want to create a new one.
Getting the DEM
Beginning DEM download and warping
DEM download finished
Beginning interpolation
Interpolation finished
Saving DEM to disk
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py:267: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  lengths = np.linalg.norm(f['LOS'].value, axis=-1)
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py:252: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  f['Rays_SLV'][:,:] = f['LOS'].value / f['Rays_len'].value[:,np.newaxis]
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py:243: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  f['Rays_SP'][:,:] = np.array(t.transform(f['lon'].value, f['lat'].value, f['hgt'].value)).T
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py:201: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  wm_proj = CRS.from_json(f['Projection'].value)
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py:78: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  xs_wm = f['x'].value.copy()
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py:79: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  ys_wm = f['y'].value.copy()
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py:80: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  zs_wm = f['z'].value.copy()
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py:81: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  wet=f['wet'].value.copy()
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py:82: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  hydro=f['hydro'].value.copy()
Traceback (most recent call last):
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/bin/raiderDelay.py", line 13, in <module>
    parseCMD()
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/runProgram.py", line 146, in parseCMD
    (_,_) = tropo_delay(los, lats, lons, heights, flag, weather_model, wmLoc, zref,
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py", line 186, in tropo_delay
    computeDelay(weather_model_file, pnts_file, zref, out,
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py", line 111, in computeDelay
    wet, hydro = interpolateDelay(weather_model_file_name, pnts_file_name, zref = zref,
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py", line 70, in interpolateDelay
    delays = RAiDER.delayFcns.get_delays(stepSize, pnts_file_name, 
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delayFcns.py", line 84, in get_delays
    ifWet = getIntFcn2(xs_wm, ys_wm, zs_wm, wet)
NameError: name 'getIntFcn2' is not defined
```
</details>

**Comment by dbekaert** [comment]
@jlmaurer merged but getting error:

<details>

```raiderDelay.py --date 20200103 --time 23:00:00 -b 40 -79 39 -78 --model ERA5 --zref 15000 -v
usage: raiderDelay.py [-h] --date DATELIST --time TIME (--area LAT LONG | --BBOX N W S E | --station_file STATION_FILE) [--lineofsight LOS | --statevectors SV] [--dem DEM | --heightlvs HEIGHTLVS [HEIGHTLVS ...]]
                      [--model MODEL] [--files FILES [FILES ...]] [--weatherModelFileLocation WMLOC] [--zref ZREF] [--outformat OUTFORMAT] [--out OUT] [--download_only] [--verbose]
Starting to run the weather model calculation
Time type: <class 'datetime.datetime'>
Time: 20200103
Flag type is bounding_box
DEM/height type is "download"
Beginning weather model pre-processing
Download-only is False
Storing weather model at: weather_files/ERA-5_2020_01_03_T23_00_00.nc
Weather model ERA-5 is available from 1950-01-01 00:00:00-Present
{'product_type': 'reanalysis', 'pressure_level': 'all', 'levtype': 'pl', 'variable': ['geopotential', 'relative_humidity', 'specific_humidity', 'temperature'], 'stream': 'oper', 'type': 'an', 'year': '2020', 'month': '1', 'day': '3', 'time': '23:00', 'step': '0', 'area': [40.4, -79.4, 38.6, -77.6], 'format': 'netcdf'}
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cds.climate.copernicus.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2020-04-17 16:54:36,631 INFO Welcome to the CDS
2020-04-17 16:54:36,631 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-pressure-levels
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cds.climate.copernicus.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2020-04-17 16:54:37,368 INFO Request is completed
2020-04-17 16:54:37,369 INFO Downloading http://136.156.132.110/cache-compute-0001/cache/data9/adaptor.mars.internal-1587167640.6250787-19154-1-ab3d092b-d8a1-4232-8ebe-3fd75f9f6153.nc to weather_files/ERA-5_2020_01_03_T23_00_00.nc (20.8K)
2020-04-17 16:54:37,891 INFO Download rate 39.8K/s                                                                                                                                                                       
/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cds.climate.copernicus.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/bin/raiderDelay.py", line 13, in <module>
    parseCMD()
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/runProgram.py", line 168, in parseCMD
    (_,_) = tropo_delay(los, lats, lons, heights, flag, weather_model, wmLoc, zref,
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/delay.py", line 159, in tropo_delay
    weather_model, lats, lons = prepareWeatherModel(weather_model, wmLoc, out, lats=lats,  
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/processWM.py", line 82, in prepareWeatherModel
    weather_model.load(f, outLats = lats, outLons = lons, los = los, zref = zref)
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/models/weatherModel.py", line 134, in load
    self._uniform_in_z(_zlevels=_zlevels)
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/models/weatherModel.py", line 568, in _uniform_in_z
    self._t= interp_along_axis(self._zs, new_zs, self._t, axis = 2)
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/interpolator.py", line 202, in interp_along_axis
    out = np.apply_along_axis(interpV, axis=axis, arr=data, old_x = oldCoord, new_x = newCoord, 
  File "<__array_function__ internals>", line 5, in apply_along_axis
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 379, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/RAiDER/interpolator.py", line 212, in interpV
    return np.interp(new_x, old_x, y, left= left, right = right, period = period)
  File "<__array_function__ internals>", line 5, in interp
  File "/Users/dbekaert/Software/python/miniconda37/envs/RAiDER/lib/python3.8/site-packages/numpy/lib/function_base.py", line 1412, in interp
    return interp_func(x, xp, fp, left, right)
ValueError: object too deep for desired array
```
</details>

**Comment by dbekaert** [comment]
@jlmaurer perged and same error as in #28
