### ISSUE TITLE
"out" not defined error for _query_points.h5 after PR 

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#276]
New issue since last PR.

```
(RAiDER-NISAR-ST) [dbekaert@leffe HRES]$ raiderDelay.py --time 06:00 --model HRES --date 20090125 20191231 84 --station_file ../GNSS/partial_stations/gnssStationList_overbbox_C_Lon0to90.csv --zref 30000 -v
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 154, in parseCMD
    args = checkArgs(args, p)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/checkArgs.py", line 42, in checkArgs
    lat, lon, llproj, bounds, flag, pnts_file = readLL(args.query_area)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/llreader.py", line 46, in readLL
    pnts_file_name = os.path.join(out, 'geom', fname + '_query_points.h5')
NameError: name 'out' is not defined
```

**Comment by dbekaert** [comment]
Even when using --out it does not work. This is not covered through unit tests.
