### ISSUE TITLE
[BUG] version 2.0 of dem-stitcher fails to import

### ISSUE THREAD

**Issue by scottstanie** [dbekaert/RAiDER#335]
**Describe the bug**
Version 2.0 (and possible 1.0) of `dem_stitcher` does not work with Raider. There is no more `download_dem` in the `stitcher.py` module:

https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/blob/dev/dem_stitcher/stitcher.py

```bash
(mapping) [scott@grace RAiDER]$ raiderDelay.py --help
Traceback (most recent call last):
  File "/home/scott/miniconda3/envs/mapping/bin/raiderDelay.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/scott/repos/RAiDER/tools/bin/raiderDelay.py", line 9, in <module>
    from RAiDER.runProgram import parseCMD
  File "/home/scott/repos/RAiDER/tools/RAiDER/runProgram.py", line 12, in <module>
    from RAiDER.delay import tropo_delay
  File "/home/scott/repos/RAiDER/tools/RAiDER/delay.py", line 23, in <module>
    from RAiDER.dem import getHeights
  File "/home/scott/repos/RAiDER/tools/RAiDER/dem.py", line 22, in <module>
    from dem_stitcher.stitcher import download_dem as download_stitched_dem
ImportError: cannot import name 'download_dem' from 'dem_stitcher.stitcher' (/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/dem_stitcher/stitcher.py)
(mapping) [scott@grace RAiDER]$ pip show dem-stitcher
Name: dem-stitcher
Version: 2.0.0
Summary: Download and merge DEM tiles for processing interferograms with ISCE2.
Home-page: https://github.com/ACCESS-Cloud-Based-InSAR/dem_stitcher
Author: Charlie Marshak, David Bekaert,
      Michael Denbina, Marc Simard
Author-email: charlie.z.marshak@jpl.nasa.gov
License: UNKNOWN
Location: /home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages
Requires: boto3, geopandas, rasterio, requests, tqdm
Required-by:
```

This is also causing tests to fail on the CI: https://app.circleci.com/pipelines/github/dbekaert/RAiDER/720/workflows/1d9eacf7-82e7-4313-b576-e305db28b341/jobs/744

I can get around this with `pip install dem-stitcher==0.0.1`, but fresh pip installs will fail with Raider.

**Desktop (please complete the following information):**
 - RAiDER git tag: [e.g. git show --summary]

```
(mapping) [scott@grace RAiDER]$  git show --summary
commit 7cf0299f045b13b00b416f31bf3f8d9f1bd825b2 (HEAD -> dev, origin/dev, origin/HEAD)
Merge: ad782f5 a5d3b92
Author: Jeremy Maurer <maurer.jeremy@gmail.com>
Date:   Thu Dec 2 16:33:41 2021 -0600

    Merge pull request #330 from dbekaert/sssangha-patch-1

    Fix bug, was expecting localtime
```
 - OS
CentOS7:
```
(mapping) [scott@grace RAiDER]$ uname -a
Linux grace 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**
Add any other context about the problem her

**Comment by jlmaurer** [comment]
Closing as currently is solved by #342
