### ISSUE TITLE
[BUG] GMAO dates earlier than 12/2017 fail with Pydap>=3.3.0

### ISSUE THREAD

**Issue by scottstanie** [dbekaert/RAiDER#336]
**Describe the bug**
I was creating a bunch of Line of sight-projected maps with GMAO using `raiderDelay.py`. The code works for Pydap version 3.2.1. 
They seem to have changed something so that it fails to grab all the data we need, and it leads to this traceback:

```
(mapping) [scott@grace igrams_looked]$ raiderDelay.py --model GMAO  --time 00:59:21 --lineofsight los_az_inc.tif -d ./elevation_looked.dem --latlon lat.geo.vrt lon.geo.vrt --out ./raider --date 20180827
Weather model GMAO is available from 2014-02-20 00:00:00-Present
WARNING: Rounded given hour from  0 to 0
ERROR: Unable to save weathermodel to file
Traceback (most recent call last):
  File "/home/scott/repos/RAiDER/tools/RAiDER/models/gmao.py", line 148, in _fetch
    writeWeatherVars2NETCDF4(self, lats, lons, h, q, p, t, outName=out)
  File "/home/scott/repos/RAiDER/tools/RAiDER/utilFcns.py", line 772, in writeWeatherVars2NETCDF4
    nc_outfile = write2NETCDF4core(nc_outfile, dimension_dict, dataset_dict, tran, mapping_name='WGS84')
  File "/home/scott/repos/RAiDER/tools/RAiDER/utilFcns.py", line 858, in write2NETCDF4core
    dataset_dict[data]['dataset'][ndmask] = FillValue
TypeError: only integer scalar arrays can be converted to a scalar index
Traceback (most recent call last):
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/pdb.py", line 1704, in main
    pdb._runscript(mainpyfile)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/scott/miniconda3/envs/mapping/bin/raiderDelay.py", line 3, in <module>
    __requires__ = 'RAiDER==0.0.1'
  File "/home/scott/repos/RAiDER/tools/bin/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/scott/repos/RAiDER/tools/RAiDER/runProgram.py", line 198, in parseCMD
    _tropo_delay(new_args)
  File "/home/scott/repos/RAiDER/tools/RAiDER/runProgram.py", line 210, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/home/scott/repos/RAiDER/tools/RAiDER/delay.py", line 73, in tropo_delay
    weather_model_file = prepareWeatherModel(
  File "/home/scott/repos/RAiDER/tools/RAiDER/processWM.py", line 84, in prepareWeatherModel
    f = weather_model.load(
  File "/home/scott/repos/RAiDER/tools/RAiDER/models/weatherModel.py", line 201, in load
    self.load_weather(*args, **kwargs)
  File "/home/scott/repos/RAiDER/tools/RAiDER/models/gmao.py", line 161, in load_weather
    self._load_model_level(f)
  File "/home/scott/repos/RAiDER/tools/RAiDER/models/gmao.py", line 173, in _load_model_level
    h = np.array(f.variables['H'][:])
KeyError: 'H'
```

Here's the data contained in an older file or with version 3.2.1:
```python
In [6]: ds2 = xr.open_dataset( "./raider/weather_files/GMAO_2014_11_21_T00_59_21.nc")

In [7]: ds2
Out[7]:
<xarray.Dataset>
Dimensions:  (x: 12, y: 15, z: 72)
Coordinates:
  * x        (x) float64 -105.6 -105.3 -105.0 -104.7 ... -102.8 -102.5 -102.2
  * y        (y) float64 30.0 30.25 30.5 30.75 31.0 ... 32.75 33.0 33.25 33.5
  * z        (z) float32 0.0 1.0 2.0 3.0 4.0 5.0 ... 67.0 68.0 69.0 70.0 71.0
Data variables:
    WGS84    |S1 ...
    H        (z, y, x) float32 ...
    QV       (z, y, x) float32 ...
    PL       (z, y, x) float32 ...
    T        (z, y, x) float32 ...
Attributes:
    Conventions:   CF-1.6
    datetime:      2014_11_21T00_59_21
    date_created:  2022_02_16T12_36_45
    title:         GMAO weather model data

```

But the newer ones created with Pydap 3.3 have a lot less data:
```python
In [4]: ds = xr.open_dataset("./raider/weather_files/GMAO_2018_08_26_T00_59_21.nc")

In [5]: ds
Out[5]:
<xarray.Dataset>
Dimensions:  (x: 12, y: 15, z: 72)
Coordinates:
  * x        (x) float64 -105.6 -105.3 -105.0 -104.7 ... -102.8 -102.5 -102.2
  * y        (y) float64 30.0 30.25 30.5 30.75 31.0 ... 32.75 33.0 33.25 33.5
  * z        (z) float32 0.0 1.0 2.0 3.0 4.0 5.0 ... 67.0 68.0 69.0 70.0 71.0
Data variables:
    WGS84    |S1 ...
    H        (z, y, x) float32 ...
Attributes:
    Conventions:   CF-1.6
    datetime:      2018_08_26T00_59_21
    date_created:  2022_02_16T13_37_39
    title:         GMAO weather model data
```

Maybe this could be an issue for https://github.com/pydap/pydap rather than here, not sure at first glance.

**Desktop (please complete the following information):**
 - RAiDER git tag: [e.g. git show --summary]

```
$  git show --summary
commit 7cf0299f045b13b00b416f31bf3f8d9f1bd825b2 (HEAD -> dev, origin/dev, origin/HEAD)
Merge: ad782f5 a5d3b92
Author: Jeremy Maurer <maurer.jeremy@gmail.com>
Date:   Thu Dec 2 16:33:41 2021 -0600

    Merge pull request #330 from dbekaert/sssangha-patch-1

    Fix bug, was expecting localtime
```

OS: centos7

**Additional context**

Pydap==3.3.0

**Comment by jlmaurer** [comment]
Leaving myself a note that I've seen this before but didn't tie it specifically to a pydap version. Will try to reproduce.

**Comment by the-garlic-os** [comment]
I'm trying to reproduce the error but I'm getting stuck on where to get the input files. How can I get the los, dem, and latlon files to test this?

**Comment by scottstanie** [comment]
ah shoot, let me try to see how I can upload them.
The area was over west Texas (approximate bounding box (-105, 30, -103, 32) ), and I assume that the lat/lon/los data won't matter because it doesn't get to the actual ray tracing part. But I can re-find these files to reproduce more easily

**Comment by jlmaurer** [comment]
@the-garlic-os I think this issue may not be tied to the specifics of the input data; I think I've had this happen with just a bounding box input. You could try that and see.

**Comment by dbekaert** [comment]
@bbuzz31 this can be closed?
