### ISSUE TITLE
[BUG] GMAO weather model issue with YML config file

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#376]
**Describe the bug**
There seems to be an issue formatting the GMAO weather model.

**To Reproduce**

Navigate to an empty directory. Create a subdirectory called `weather_files`.

```
raiderDelay.py test.yml
```
with `test.yml` as:

```
look_dir: right

date_group:
  date_start:
  date_end:
  date_step:
  date_list:  [20200101]

time_group:
  time: "22:00:00"
  end_time:

weather_model: GMAO

aoi_group:
  lat_file:
  lon_file:
  height_file_rdr:
  station_file:
  bounding_box: 53.0 56.0 -4.0 -1.0
  utm_zone:
  grid_x:
  grid_y:

height_group:
  dem:
  use_dem_latlon: False
  height_file_rdr:
  height_levels: "-500 0 500 1000 1500 2000 2500 3000 3500 4000 4500 5000 5500 6000 6500 7000 7500 8000 8500 9000"

los_group:
  ray_trace: False  # Use projected slant delay by default
  zref: # Integration height. Only used in raytracing.
  los_file:
  los_convention: isce  # can be "isce" or "hyp3", see *** for details
  los_cube:
  orbit_file:

runtime_group:
  verbose: True
  raster_format: nc # Can be any rasterio-compatible format
  output_directory: '.'
  weather_model_directory: weather_files
  cube_spacing_in_m: 2000.
```

The error is:
```
(RAiDER) --- bekaert-team/raider-example » raiderDelay.py test.yml
Run routine processing with raiderDelay.py on steps: ['load_weather_model', 'calculate_delays']
Remaining steps: ['calculate_delays']
--------------------------------------------------
Weather model GMAO is available from 2014-02-20 00:00:00-Present
WARNING: Rounded given hour from  22 to 21
/Users/cmarshak/opt/anaconda3/envs/RAiDER/lib/python3.11/site-packages/pyproj/crs/crs.py:1286: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj = self._crs.to_proj4(version=version)
ERROR: Unable to save weathermodel to file
Traceback (most recent call last):
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/models/gmao.py", line 145, in _fetch
    writeWeatherVars2NETCDF4(self, lats, lons, h, q, p, t, outName=out)
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/utilFcns.py", line 826, in writeWeatherVars2NETCDF4
    nc_outfile = write2NETCDF4core(nc_outfile, dimension_dict, dataset_dict, tran, mapping_name='WGS84')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/utilFcns.py", line 906, in write2NETCDF4core
    dataset_dict[data]['dataset'][ndmask] = FillValue
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: only integer scalar arrays can be converted to a scalar index
Traceback (most recent call last):
  File "/Users/cmarshak/opt/anaconda3/envs/RAiDER/bin/raiderDelay.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/runProgram.py", line 33, in main
    (_, _) = tropo_delay(t, w, f, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/delay.py", line 90, in tropo_delay
    weather_model_file = prepareWeatherModel(
                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/processWM.py", line 77, in prepareWeatherModel
    f = weather_model.load(
        ^^^^^^^^^^^^^^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/models/weatherModel.py", line 201, in load
    self.load_weather(*args, **kwargs)
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/models/gmao.py", line 158, in load_weather
    self._load_model_level(f)
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/models/gmao.py", line 170, in _load_model_level
    h = np.array(f.variables['H'][:])
                 ~~~~~~~~~~~^^^^^
KeyError: 'H'
```

**Expected behavior**
Not sure

**Comment by cmarshak** [comment]
```
(RAiDER) --- bekaert-team/raider-example » conda info             1 ↵

     active environment : RAiDER
    active env location : /Users/cmarshak/opt/anaconda3/envs/RAiDER
            shell level : 2
       user config file : /Users/cmarshak/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/cmarshak/opt/anaconda3  (writable)
      conda av data dir : /Users/cmarshak/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/cmarshak/opt/anaconda3/pkgs
                          /Users/cmarshak/.conda/pkgs
       envs directories : /Users/cmarshak/opt/anaconda3/envs
                          /Users/cmarshak/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.28.1 CPython/3.8.5 Darwin/21.6.0 OSX/10.16
                UID:GID : 29783585:20
             netrc file : /Users/cmarshak/.netrc
           offline mode : False
```
and

```
# conda environments:
#
base                     /Users/cmarshak/opt/anaconda3
ARIA-tools               /Users/cmarshak/opt/anaconda3/envs/ARIA-tools
RAiDER                *  /Users/cmarshak/opt/anaconda3/envs/RAiDER
dem-stitcher             /Users/cmarshak/opt/anaconda3/envs/dem-stitcher
dswx-calval-env          /Users/cmarshak/opt/anaconda3/envs/dswx-calval-env
dswx_val                 /Users/cmarshak/opt/anaconda3/envs/dswx_val
fastapi                  /Users/cmarshak/opt/anaconda3/envs/fastapi
gdal                     /Users/cmarshak/opt/anaconda3/envs/gdal
herbie                   /Users/cmarshak/opt/anaconda3/envs/herbie
hrrr                     /Users/cmarshak/opt/anaconda3/envs/hrrr
imagemagick              /Users/cmarshak/opt/anaconda3/envs/imagemagick
rscube                   /Users/cmarshak/opt/anaconda3/envs/rscube
s1-enumerator            /Users/cmarshak/opt/anaconda3/envs/s1-enumerator
tiles                    /Users/cmarshak/opt/anaconda3/envs/tiles
topsapp_env              /Users/cmarshak/opt/anaconda3/envs/topsapp_env
xarray                   /Users/cmarshak/opt/anaconda3/envs/xarray
xarray_demo              /Users/cmarshak/opt/anaconda3/envs/xarray_demo
```

**Comment by cmarshak** [comment]
Also note the warning `WARNING: Rounded given hour from  22 to 21`.

**Comment by cmarshak** [comment]
Per #377 - I updated the yml file, but the same error persisted. I am including the updated yml file here for posterity.

```
look_dir: right

date_group:
  date_start:
  date_end:
  date_step:
  date_list:  [20200101]

time_group:
  time: "23:00:00"
  end_time:

weather_model: GMAO

aoi_group:
  lat_file:
  lon_file:
  height_file_rdr:
  station_file:
  bounding_box: 53.0 56.0 -4.0 -1.0
  utm_zone:
  grid_x:
  grid_y:

height_group:
  dem:
  use_dem_latlon: False
  height_file_rdr:
  height_levels: "-500 0 500 1000 1500 2000 2500 3000 3500 4000 4500 5000 5500 6000 6500 7000 7500 8000 8500 9000"

los_group:
  ray_trace: False  # Use projected slant delay by default
  zref: # Integration height. Only used in raytracing.
  los_file:
  los_convention: isce  # can be "isce" or "hyp3", see *** for details
  los_cube:
  orbit_file:

runtime_group:
  verbose: True
  raster_format: nc # Can be any rasterio-compatible format
  output_directory: .
  weather_model_directory: weather_files
  cube_spacing_in_m: 2000.
  output_projection:  4326
```
