### ISSUE TITLE
[BUG] ERA-5 Issue after Download with YML file

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#377]
**Describe the bug**
```
(RAiDER) --- bekaert-team/raider-example » raiderDelay.py test.yml
Run routine processing with raiderDelay.py on steps: ['load_weather_model', 'calculate_delays']
Remaining steps: ['calculate_delays']
--------------------------------------------------
Weather model ERA-5 is available from 1950-01-01 00:00:00-Present
/Users/cmarshak/opt/anaconda3/envs/RAiDER/lib/python3.11/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cds.climate.copernicus.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-11-08 11:30:01,386 INFO Welcome to the CDS
2022-11-08 11:30:01,386 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-complete
/Users/cmarshak/opt/anaconda3/envs/RAiDER/lib/python3.11/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cds.climate.copernicus.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-11-08 11:30:01,595 INFO Request is completed
2022-11-08 11:30:01,596 INFO Downloading https://download-0004-clone.copernicus-climate.eu/cache-compute-0004/cache/data1/adaptor.mars.external-1667935716.7825692-21824-6-5a46159a-9c19-4afe-8f36-89ee9a62fff4.nc to weather_files/ERA-5_2020_01_01_T22_00_00.nc (38.7K)
/Users/cmarshak/opt/anaconda3/envs/RAiDER/lib/python3.11/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'download-0004-clone.copernicus-climate.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-11-08 11:30:02,689 INFO Download rate 35.4K/s
/Users/cmarshak/opt/anaconda3/envs/RAiDER/lib/python3.11/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cds.climate.copernicus.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-11-08 11:30:03,245 DEBUG Number of weather model nodes: 5408
2022-11-08 11:30:03,245 DEBUG Shape of weather model: (13, 13, 32)
2022-11-08 11:30:03,245 DEBUG Bounds of the weather model: 53.00/56.00/-4.00/-1.00 (SNWE)
2022-11-08 11:30:03,245 DEBUG Weather model: ERA-5
2022-11-08 11:30:03,246 DEBUG Mean value of the wet refractivity: 12.680276
2022-11-08 11:30:03,246 DEBUG Mean value of the hydrostatic refractivity: 139.594299
2022-11-08 11:30:03,246 DEBUG
======Weather Model class object=====
Weather model time: 2020-01-01 22:00:00
Latitude resolution: 0.2
Longitude resolution: 0.2
Native projection: epsg:4326
ZMIN: -100.0
ZMAX: 15000.0
k1 = 0.776
k2 = 0.233
k3 = 3750.0
Humidity type = q
=====================================
Class name: ea
Dataset: era5
=====================================
A: []
B: []
Number of points in Lon/Lat = 13/13
Total number of grid points (3D): 5408
=====================================

/Users/cmarshak/opt/anaconda3/envs/RAiDER/lib/python3.11/site-packages/pyproj/crs/crs.py:1286: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj = self._crs.to_proj4(version=version)
2022-11-08 11:30:05,221 DEBUG Starting to run the weather model cube calculation
2022-11-08 11:30:05,221 DEBUG Time: 2020-01-01 22:00:00
2022-11-08 11:30:05,221 DEBUG Output height range is -500.0 to 9000.0
2022-11-08 11:30:05,221 DEBUG Max integration height is 15000.0 m
2022-11-08 11:30:05,221 DEBUG Output cube projection is GEOGCRS["Hu Tzu Shan 1950",DATUM["Hu Tzu Shan 1950",ELLIPSOID["International 1924",6378388,297,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],CS[ellipsoidal,2],AXIS["geodetic latitude (Lat)",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433]],AXIS["geodetic longitude (Lon)",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433]],USAGE[SCOPE["Geodesy."],AREA["Taiwan, Republic of China - onshore - Taiwan Island, Penghu (Pescadores) Islands."],BBOX[21.87,119.25,25.34,122.06]],ID["EPSG",4236]]
2022-11-08 11:30:05,221 DEBUG Output cube spacing is 250.0 m
2022-11-08 11:30:05,221 DEBUG Beginning weather model pre-processing
WARNING: I can't find a CRS in the weather model file, so I will assume you are using WGS84
Traceback (most recent call last):
  File "/Users/cmarshak/opt/anaconda3/envs/RAiDER/bin/raiderDelay.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/runProgram.py", line 33, in main
    (_, _) = tropo_delay(t, w, f, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/delay.py", line 121, in tropo_delay
    tropo_delay_cube(dt, wf, args,
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/delay.py", line 302, in tropo_delay_cube
    xpts = np.arange(out_snwe[2], out_snwe[3] + out_spacing, out_spacing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Maximum allowed size exceeded
```

**To Reproduce**

Navigate to empty directory and create `weather_files` subdirectory. Then, run:

`raiderDelay.py test.yml`

with `test.yml` as

```
look_dir: right

date_group:
  date_start:
  date_end:
  date_step:
  date_list:  [20200101]

time_group:
  time: "22:00:00"
  end_time:

weather_model: ERA-5

aoi_group:
  lat_file:
  lon_file:
  height_file_rdr:
  station_file:
  bounding_box: 53.0 56.0 -4.0 -1.0
  utm_zone:
  grid_x:
  grid_y:

height_group:
  dem:
  use_dem_latlon:
  height_file_rdr:
  height_levels: "-500 0 500 1000 1500 2000 2500 3000 3500 4000 4500 5000 5500 6000 6500 7000 7500 8000 8500 9000"

los_group:
  ray_trace: False  # Use projected slant delay by default
  zref: # Integration height. Only used in raytracing.
  los_file:
  los_convention: isce  # can be "isce" or "hyp3", see *** for details
  los_cube:
  orbit_file:

runtime_group:
  verbose: True
  raster_format: nc # Can be any rasterio-compatible format
  output_directory: '.'
  weather_model_directory: weather_files
  cube_spacing_in_m: 2000.
```

See #376 for details on environment.

**Comment by piyushrpt** [comment]
I would include `output_projection` and work of the PR that is open. These issues have been addressed by the changes in the PR I think.

**Comment by cmarshak** [comment]
Yes, using `feat/cube` branch fixed it with output projection.

```
look_dir: right

date_group:
  date_start:
  date_end:
  date_step:
  date_list:  [20200101]

time_group:
  time: "23:00:00"
  end_time:

weather_model: GMAO

aoi_group:
  lat_file:
  lon_file:
  height_file_rdr:
  station_file:
  bounding_box: 53.0 56.0 -4.0 -1.0
  utm_zone:
  grid_x:
  grid_y:

height_group:
  dem:
  use_dem_latlon: False
  height_file_rdr:
  height_levels: "-500 0 500 1000 1500 2000 2500 3000 3500 4000 4500 5000 5500 6000 6500 7000 7500 8000 8500 9000"

los_group:
  ray_trace: False  # Use projected slant delay by default
  zref: # Integration height. Only used in raytracing.
  los_file:
  los_convention: isce  # can be "isce" or "hyp3", see *** for details
  los_cube:
  orbit_file:

runtime_group:
  verbose: True
  raster_format: nc # Can be any rasterio-compatible format
  output_directory: .
  weather_model_directory: weather_files
  cube_spacing_in_m: 2000.
  output_projection:  4326
```

And to confirm @piyushrpt , I get a cube with `hydro` and `wet` 3d cube from the above.
