### ISSUE TITLE
[BUG] Sample YML in Docs is not working

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#378]
**Describe the bug**

`raiderDelay.py test.yml` with `test.yml` as:

```
look_dir: right
date_group: # Groups mean that there are several different possible options, see documentation for details
  date_start: 20200101
time_group:
  time: 12:00:00 # UTC time
weather_model: ERA-5 # RAiDER supports several models, including ECMWF, HRRR, GMAO, and MERRA-2
aoi_group:
  bounding_box: 36 37 -91 -92 # bounding box uses the weather model grid nodes
height_group:
  height_levels: 0 50 100 500 1000 # Return only these specific height levels
los_group: # absent other options ZTD is calculated
runtime_group:
  verbose: True
  raster_format: GTiff # Can be any rasterio-compatible format
```

per: https://github.com/jlmaurer/RAiDER-docs/blob/new_branch/notebooks/RAiDER_tutorial/raider_example_1.yaml

gives
```
(RAiDER) --- bekaert-team/raider-example » raiderDelay.py test.yml
Run routine processing with raiderDelay.py on steps: ['load_weather_model', 'calculate_delays']
Remaining steps: ['calculate_delays']
--------------------------------------------------
Traceback (most recent call last):
  File "/Users/cmarshak/opt/anaconda3/envs/RAiDER/bin/raiderDelay.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/runProgram.py", line 18, in main
    params = read_template_file(inps.customTemplateFile)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/cli/raiderDelay.py", line 220, in read_template_file
    params = drop_nans(params)
             ^^^^^^^^^^^^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/cli/raiderDelay.py", line 259, in drop_nans
    for key, value in d.items():
RuntimeError: dictionary changed size during iteration
```

**Comment by jlmaurer** [comment]
Closing this here and also updated at [RAiDER-docs](https://github.com/dbekaert/RAiDER-docs/pull/25)
