### ISSUE TITLE
[BUG] Orbit and raytracing doesn't work

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#381]
**Describe the bug**
```
raiderDelay.yml test-orbit.yml
```

This is `test-orbit.yml` (the aoi is over Europe and intersects the SLC linked below):

```
look_dir: right

date_group:
  date_start:
  date_end:
  date_step:
  date_list:  [20211102]

time_group:
  time: "06:21:59"
  end_time:

weather_model: ERA-5

aoi_group:
  lat_file:
  lon_file:
  height_file_rdr:
  station_file:
  bounding_box: 53.0 56.0 -4.0 -1.0
  utm_zone:
  grid_x:
  grid_y:

height_group:
  dem:
  use_dem_latlon: False
  height_file_rdr:
  height_levels: "-500 0 500 1000 1500 2000 2500 3000 3500 4000 4500 5000 5500 6000 6500 7000 7500 8000 8500 9000"

los_group:
  ray_trace: True  # Use projected slant delay by default
  zref: # Integration height. Only used in raytracing.
  los_file:
  los_convention: isce  # can be "isce" or "hyp3", see *** for details
  los_cube:
  orbit_file: S1B_OPER_AUX_POEORB_OPOD_20211122T112354_V20211101T225942_20211103T005942.EOF

runtime_group:
  verbose: True
  raster_format: nc # Can be any rasterio-compatible format
  output_directory: .
  weather_model_directory: weather_files
  cube_spacing_in_m: 2000.
  output_projection:  4326
```

The error is this:
```
2022-11-08 14:17:38,652 DEBUG Output cube spacing: 0.02
WARNING: I can't find a CRS in the weather model file, so I will assume you are using WGS84
2022-11-08 14:17:39,154 DEBUG Look direction: right
Processing slice 1 / 20: -500.0
2022-11-08 14:17:39,170 INFO Processing slice 1 / 20: -500.0
Traceback (most recent call last):
  File "/Users/cmarshak/opt/anaconda3/envs/RAiDER/bin/raiderDelay.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/runProgram.py", line 33, in main
    (_, _) = tropo_delay(t, w, f, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/delay.py", line 106, in tropo_delay
    tropo_delay_cube(dt, wf, args, model_file=weather_model_file)
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/delay.py", line 335, in tropo_delay_cube
    wetDelay, hydroDelay = build_cube_ray(
                           ^^^^^^^^^^^^^^^
  File "/Users/cmarshak/bekaert-team/RAiDER/tools/RAiDER/delay.py", line 633, in build_cube_ray
    nParts = int(np.ceil(ray_length.max() / MAX_SEGMENT_LENGTH)) + 1
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
```
**To Reproduce**

I downloaded the orbit using this https://github.com/scottstanie/sentineleof

```
In [1]: from eof.download import download_eofs

In [2]: download_eofs(['20211102'], ['S1B'])
```

The relevant SLC intersecting the bounding box is here: https://search.asf.alaska.edu/#/?zoom=6.385&center=-1.101,51.242&resultsLoaded=true&granule=S1B_IW_SLC__1SDV_20211102T062159_20211102T062227_029405_03825F_77F9-SLC&searchType=List%20Search&searchList=S1B_IW_SLC__1SDV_20211102T062159_20211102T062227_029405_03825F_77F9

The initial acquisition time is determined from the SLC name and then put into the yml file.

**Comment by jlmaurer** [comment]
this should have been fixed by #383
