### ISSUE TITLE
downloadGNSS.py and raiderDownloadGNSS.py entrypoints are broken

### ISSUE THREAD

**Issue by jhkennedy** [dbekaert/RAiDER#453]
Both `downloadGNSS.py` and `raiderDownloadGNSS.py` entry points raise a `NameError` when run with the `--help` option:

```shell
$ downloadGNSS.py -h
Traceback (most recent call last):
  File "$HOME/mambaforge/envs/RAiDER/bin/downloadGNSS.py", line 8, in <module>
    sys.exit(downloadGNSS())
  File "$HOME/Documents/Code/contributing/RAiDER/tools/RAiDER/cli/raider.py", line 411, in downloadGNSS
    add_out(misc)
NameError: name 'add_out' is not defined

```

and 

```shell
$ raiderDownloadGNSS.py -h
Traceback (most recent call last):
  File "$HOME/mambaforge/envs/RAiDER/bin/raiderDownloadGNSS.py", line 8, in <module>
    sys.exit(downloadGNSS())
  File "$HOME/Documents/Code/contributing/RAiDER/tools/RAiDER/cli/raider.py", line 411, in downloadGNSS
    add_out(misc)
NameError: name 'add_out' is not defined

```

Also, these entry points both [point to the same function](https://github.com/dbekaert/RAiDER/blob/dev/pyproject.toml#L47-L48). Any reason they are duplicated?

**Comment by bbuzz31** [comment]
Thanks for the catch… they’re duplicated deliberately to maintain backward compatability (i think for SWOT users)
