### ISSUE TITLE
`KeyError: NCMR` exception when running calcDelaysGUNW with `--weather-model=NCMR`

### ISSUE THREAD

**Issue by asjohnston-asf** [dbekaert/RAiDER#485]
The new weather model was not added to the dictionary at https://github.com/dbekaert/RAiDER/blob/dev/tools/RAiDER/aria/prepFromGUNW.py#L21

```
$ raider.py ++process calcDelaysGUNW --weather-model NCMR --file /home/asjohnston/Downloads/S1-GUNW-A-R-048-tops-20210422_20210410-232959-32707N_30657N-PP-c28e-v2_0_5.nc
Traceback (most recent call last):
  File "/home/asjohnston/mambaforge/envs/RAiDER/bin/raider.py", line 8, in <module>
    sys.exit(main())
  File "/home/asjohnston/src/RAiDER/tools/RAiDER/cli/__main__.py", line 29, in main
    process_entry_point.load()()
  File "/home/asjohnston/src/RAiDER/tools/RAiDER/cli/raider.py", line 433, in calcDelaysGUNW
    path_cfg, wavelength = GUNW_prep(args)
  File "/home/asjohnston/src/RAiDER/tools/RAiDER/aria/prepFromGUNW.py", line 234, in main
    GUNWObj = GUNW(args.file, args.weather_model, args.output_directory)
  File "/home/asjohnston/src/RAiDER/tools/RAiDER/aria/prepFromGUNW.py", line 29, in __init__
    self.spacing_m = int(DCT_POSTING[self.wmodel] * 1e5)
KeyError: 'NCMR'
```

**Comment by dbekaert** [comment]
Addressed under #486. Leaving this open for @jlmaurer to add support back in with tests
