### ISSUE TITLE
[BUG] - RAIDER + ERA5 Fails over Hawaii

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#503]
**Describe the bug**
Here is a list of failed jobs.

```
[{'job_id': 'baf54612-cc8c-4182-9fb0-f7e6f06ad490',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19224,
   'granules': ['S1A_IW_SLC__1SDV_20230217T043052_20230217T043122_047271_05AC44_293F',
    'S1A_IW_SLC__1SDV_20230217T043119_20230217T043147_047271_05AC44_56B5'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230205T043052_20230205T043122_047096_05A65E_2987',
    'S1A_IW_SLC__1SDV_20230205T043120_20230205T043148_047096_05A65E_5D6F'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/baf54612-cc8c-4182-9fb0-f7e6f06ad490/baf54612-cc8c-4182-9fb0-f7e6f06ad490.log'],
  'expiration_time': '2023-09-11T00:00:00+00:00',
  'processing_times': [7254.499, 7.754]},
 {'job_id': '3890a1c2-27c3-4d2e-83c6-854ab139bdbe',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19223,
   'granules': ['S1A_IW_SLC__1SDV_20230301T043052_20230301T043122_047446_05B233_640C'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230217T043052_20230217T043122_047271_05AC44_293F'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/3890a1c2-27c3-4d2e-83c6-854ab139bdbe/3890a1c2-27c3-4d2e-83c6-854ab139bdbe.log'],
  'expiration_time': '2023-09-11T00:00:00+00:00',
  'processing_times': [6618.724, 7.231]},
 {'job_id': '36a4ca80-518e-4dc5-9aa2-35d9bf75d44f',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19224,
   'granules': ['S1A_IW_SLC__1SDV_20230301T043052_20230301T043122_047446_05B233_640C',
    'S1A_IW_SLC__1SDV_20230301T043120_20230301T043148_047446_05B233_4BB2'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230205T043052_20230205T043122_047096_05A65E_2987',
    'S1A_IW_SLC__1SDV_20230205T043120_20230205T043148_047096_05A65E_5D6F'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/36a4ca80-518e-4dc5-9aa2-35d9bf75d44f/36a4ca80-518e-4dc5-9aa2-35d9bf75d44f.log'],
  'expiration_time': '2023-09-11T00:00:00+00:00',
  'processing_times': [7367.003, 6.962]},
 {'job_id': '5a25ee0c-4181-418d-886e-d76f3842ea03',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19223,
   'granules': ['S1A_IW_SLC__1SDV_20230313T043052_20230313T043122_047621_05B821_6C6B'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230301T043052_20230301T043122_047446_05B233_640C'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/5a25ee0c-4181-418d-886e-d76f3842ea03/5a25ee0c-4181-418d-886e-d76f3842ea03.log'],
  'expiration_time': '2023-09-11T00:00:00+00:00',
  'processing_times': [6375.173, 6.932]},
 {'job_id': '1a48177d-27e4-4f95-8d2e-225a278b0beb',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19223,
   'granules': ['S1A_IW_SLC__1SDV_20230301T043052_20230301T043122_047446_05B233_640C'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230205T043052_20230205T043122_047096_05A65E_2987'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/1a48177d-27e4-4f95-8d2e-225a278b0beb/1a48177d-27e4-4f95-8d2e-225a278b0beb.log'],
  'expiration_time': '2023-09-12T00:00:00+00:00',
  'processing_times': [6597.056, 6.977]},
 {'job_id': '25cce73f-40cc-4372-9d53-c7b10f334c8d',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19224,
   'granules': ['S1A_IW_SLC__1SDV_20230313T043052_20230313T043122_047621_05B821_6C6B',
    'S1A_IW_SLC__1SDV_20230313T043120_20230313T043147_047621_05B821_C01A'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230217T043052_20230217T043122_047271_05AC44_293F',
    'S1A_IW_SLC__1SDV_20230217T043119_20230217T043147_047271_05AC44_56B5'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/25cce73f-40cc-4372-9d53-c7b10f334c8d/25cce73f-40cc-4372-9d53-c7b10f334c8d.log'],
  'expiration_time': '2023-09-11T00:00:00+00:00',
  'processing_times': [249.222]},
 {'job_id': '27be723b-7786-4f44-bf0c-81c985192d84',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19223,
   'granules': ['S1A_IW_SLC__1SDV_20230313T043052_20230313T043122_047621_05B821_6C6B'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230217T043052_20230217T043122_047271_05AC44_293F'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/27be723b-7786-4f44-bf0c-81c985192d84/27be723b-7786-4f44-bf0c-81c985192d84.log'],
  'expiration_time': '2023-09-11T00:00:00+00:00',
  'processing_times': [6381.784, 6.847]},
 {'job_id': '536055fb-f3c9-49b9-ab8b-a3348eb9652b',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19223,
   'granules': ['S1A_IW_SLC__1SDV_20230217T043052_20230217T043122_047271_05AC44_293F'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230205T043052_20230205T043122_047096_05A65E_2987'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/536055fb-f3c9-49b9-ab8b-a3348eb9652b/536055fb-f3c9-49b9-ab8b-a3348eb9652b.log'],
  'expiration_time': '2023-09-11T00:00:00+00:00',
  'processing_times': [6418.539, 7.887]},
 {'job_id': 'faee86e3-4f28-47b6-9a21-ce2523acc1c4',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19224,
   'granules': ['S1A_IW_SLC__1SDV_20230301T043052_20230301T043122_047446_05B233_640C',
    'S1A_IW_SLC__1SDV_20230301T043120_20230301T043148_047446_05B233_4BB2'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230217T043052_20230217T043122_047271_05AC44_293F',
    'S1A_IW_SLC__1SDV_20230217T043119_20230217T043147_047271_05AC44_56B5'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/faee86e3-4f28-47b6-9a21-ce2523acc1c4/faee86e3-4f28-47b6-9a21-ce2523acc1c4.log'],
  'expiration_time': '2023-09-11T00:00:00+00:00',
  'processing_times': [7542.938, 7.14]},
 {'job_id': '09998c9d-6e34-42d1-b4ae-c316dc36815f',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19224,
   'granules': ['S1A_IW_SLC__1SDV_20230313T043052_20230313T043122_047621_05B821_6C6B',
    'S1A_IW_SLC__1SDV_20230313T043120_20230313T043147_047621_05B821_C01A'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230301T043052_20230301T043122_047446_05B233_640C',
    'S1A_IW_SLC__1SDV_20230301T043120_20230301T043148_047446_05B233_4BB2'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/09998c9d-6e34-42d1-b4ae-c316dc36815f/09998c9d-6e34-42d1-b4ae-c316dc36815f.log'],
  'expiration_time': '2023-09-11T00:00:00+00:00',
  'processing_times': [7247.556, 6.951]}]
```

You can download the GUNW (without tropo) replacing the `*.log` file with the GUNW ID (looking at the log file). They will be available for 1 week. Download them now.

Here is an example from the last job.

https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/09998c9d-6e34-42d1-b4ae-c316dc36815f/S1-GUNW-A-R-124-tops-20230313_20230301-043119-00157W_00019N-PP-7d06-v2_0_6.nc

Here is an output from the last log. Not sure what the latency is - some of the jobs using SLC data from yesterday fail (understandable), but this one seems like it should be available. Thanks for your help @bbuzz31 

```
Downloading s3://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b/baf54612-cc8c-4182-9fb0-f7e6f06ad490/S1-GUNW-A-R-124-tops-20230217_20230205-043119-00157W_00019N-PP-5f23-v2_0_6.nc to S1-GUNW-A-R-124-tops-20230217_20230205-043119-00157W_00019N-PP-5f23-v2_0_6.nc
Writing /home/raider/.cdsapirc locally!

Downloading products:   0%|          | 0/1 [00:00<?, ?product/s]

Downloading S1A_OPER_AUX_POEORB_OPOD_20230309T080810_V20230216T225942_20230218T005942.EOF:   0%|          | 0.00/4.65M [00:00<?, ?B/s][A

Downloading S1A_OPER_AUX_POEORB_OPOD_20230309T080810_V20230216T225942_20230218T005942.EOF:  23%|â–ˆâ–ˆâ–Ž       | 1.05M/4.65M [00:00<00:03, 1.09MB/s][A

Downloading S1A_OPER_AUX_POEORB_OPOD_20230309T080810_V20230216T225942_20230218T005942.EOF:  45%|â–ˆâ–ˆâ–ˆâ–ˆâ–Œ     | 2.10M/4.65M [00:01<00:01, 2.14MB/s][A

Downloading S1A_OPER_AUX_POEORB_OPOD_20230309T080810_V20230216T225942_20230218T005942.EOF:  90%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ | 4.19M/4.65M [00:01<00:00, 4.50MB/s][A
Downloading S1A_OPER_AUX_POEORB_OPOD_20230309T080810_V20230216T225942_20230218T005942.EOF: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4.65M/4.65M [00:01<00:00, 3.62MB/s]

MD5 checksumming:   0%|          | 0.00/4.65M [00:00<?, ?B/s][A

                                                             [A
Downloading products: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:01<00:00,  1.99s/product]
Downloading products: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:01<00:00,  1.99s/product]
Wrote new cfg file: GUNW_20230217-20230205.yaml
[33;21mWARNING: Weather model only extends to the surface topography; height levels below the topography will be interpolated from the surface and may be inaccurate.[0m
Invalid extension GTiff for cube. Defaulting to .nc
Invalid extension GTiff for cube. Defaulting to .nc
Starting to run the weather model calculation
Date: 20230217
Beginning weather model pre-processing
Weather model ERA-5 is available from 1950-01-01 00:00:00-Present
[31;21mERROR: Date 2023-02-17 04:31:34 failed[0m
Traceback (most recent call last):
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/raider.py", line 235, in calcDelays
    prepareWeatherModel(
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/processWM.py", line 61, in prepareWeatherModel
    weather_model.fetch(*weather_model.files, ll_bounds, time)
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/models/weatherModel.py", line 148, in fetch
    self.checkTime(time)
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/models/weatherModel.py", line 277, in checkTime
    raise RuntimeError("Weather model {} is not available at {}".format(self.Model(), time))
RuntimeError: Weather model ERA-5 is not available at 2023-02-17 04:00:00
Weather model ERA-5 is available from 1950-01-01 00:00:00-Present
[31;21mERROR: Date 2023-02-17 04:31:34 failed[0m
Traceback (most recent call last):
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/raider.py", line 235, in calcDelays
    prepareWeatherModel(
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/processWM.py", line 61, in prepareWeatherModel
    weather_model.fetch(*weather_model.files, ll_bounds, time)
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/models/weatherModel.py", line 148, in fetch
    self.checkTime(time)
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/models/weatherModel.py", line 277, in checkTime
    raise RuntimeError("Weather model {} is not available at {}".format(self.Model(), time))
RuntimeError: Weather model ERA-5 is not available at 2023-02-17 05:00:00
Traceback (most recent call last):
  File "/opt/conda/envs/RAiDER/bin/raider.py", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/__main__.py", line 29, in main
    process_entry_point.load()()
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/raider.py", line 486, in calcDelaysGUNW
    cube_filenames = calcDelays([path_cfg])
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/raider.py", line 276, in calcDelays
    weather_model_file = wfiles[0]
IndexError: list index out of range
```

**Comment by cmarshak** [comment]
So, one of the jobs above actually fails in the ISCE2 step because there is only one processing time.

```
{'job_id': '25cce73f-40cc-4372-9d53-c7b10f334c8d',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-14T19:23:25+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii_124_ERA5_0314',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 19224,
   'granules': ['S1A_IW_SLC__1SDV_20230313T043052_20230313T043122_047621_05B821_6C6B',
    'S1A_IW_SLC__1SDV_20230313T043120_20230313T043147_047621_05B821_C01A'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20230217T043052_20230217T043122_047271_05AC44_293F',
    'S1A_IW_SLC__1SDV_20230217T043119_20230217T043147_047271_05AC44_56B5'],
   'weather_model': 'ERA5'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/25cce73f-40cc-4372-9d53-c7b10f334c8d/25cce73f-40cc-4372-9d53-c7b10f334c8d.log'],
  'expiration_time': '2023-09-11T00:00:00+00:00',
  'processing_times': [249.222]}
```

**Comment by bbuzz31** [comment]
The above fail for ERA5 because of data latency.

"Initial release data, i.e. data no more than three months behind real time, is called ERA5T."

**Comment by dbekaert** [comment]
@cmarshak few things which we can discuss in our next meeting?
- for our enumerator is there a way to import or copy over the model validity period and catch it earlier at enumeration stage?
- I understand if the product is made sucessfull but the tropo fails, we cannot publish to ASF?


@bbuzz31 I understand from the change log that in the current dev branch the code would error out if one or two delays were not written?

**Comment by bbuzz31** [comment]
@dbekaert Yes that is correct, although that error is actually not being reached here.

We loop over each datetime, and try to get the weather model, continuing if it errors out. 
Then we try and calculate delays on whatever weather models we have. Since we have 0 weather model files, it cant find any an errors out. 
Seems like we should have a more explanatory catch.

**Comment by dbekaert** [comment]
> Yes - so we are going to have a steady drip of testing globally to make sure both plugin steps are highly reliable.

So default behavior is that if tropo fails we dont deliver; that sounds correct to me.
