### ISSUE TITLE
[BUG] Appears to be some bugs with interpolation

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#505]
**Describe the bug**

Here is an example bug:

```
Downloading s3://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b/2985e764-669a-41cd-98cb-d04a29c0afad/S1-GUNW-A-R-004-tops-20220213_20220201-230632-00078W_00035N-PP-45ad-v2_0_6.nc to S1-GUNW-A-R-004-tops-20220213_20220201-230632-00078W_00035N-PP-45ad-v2_0_6.nc
Writing /home/raider/.netrc locally!

Downloading products:   0%|          | 0/1 [00:00<?, ?product/s]

Downloading S1A_OPER_AUX_POEORB_OPOD_20220306T081614_V20220213T225942_20220215T005942.EOF:   0%|          | 0.00/4.41M [00:00<?, ?B/s][A

Downloading S1A_OPER_AUX_POEORB_OPOD_20220306T081614_V20220213T225942_20220215T005942.EOF:  24%|â–ˆâ–ˆâ–       | 1.05M/4.41M [00:00<00:03, 1.11MB/s][A

Downloading S1A_OPER_AUX_POEORB_OPOD_20220306T081614_V20220213T225942_20220215T005942.EOF:  48%|â–ˆâ–ˆâ–ˆâ–ˆâ–Š     | 2.10M/4.41M [00:01<00:01, 2.17MB/s][A

Downloading S1A_OPER_AUX_POEORB_OPOD_20220306T081614_V20220213T225942_20220215T005942.EOF:  95%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ| 4.19M/4.41M [00:01<00:00, 4.57MB/s][A
Downloading S1A_OPER_AUX_POEORB_OPOD_20220306T081614_V20220213T225942_20220215T005942.EOF: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4.41M/4.41M [00:01<00:00, 3.49MB/s]

MD5 checksumming:   0%|          | 0.00/4.41M [00:00<?, ?B/s][A

                                                             [A
Downloading products: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:01<00:00,  1.95s/product]
Downloading products: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:01<00:00,  1.95s/product]
Wrote new cfg file: GUNW_20220213-20220201.yaml
[33;21mWARNING: Weather model only extends to the surface topography; height levels below the topography will be interpolated from the surface and may be inaccurate.[0m
Invalid extension GTiff for cube. Defaulting to .nc
Invalid extension GTiff for cube. Defaulting to .nc
Starting to run the weather model calculation
Date: 20220213
Beginning weather model pre-processing
Weather model GMAO is available from 2014-02-20 00:00:00-Present
Number of weather model nodes: 66700
Shape of weather model: (20, 23, 145)
Bounds of the weather model: 33.50/38.25/-80.31/-73.44 (SNWE)
Weather model: GMAO
Mean value of the wet refractivity: 10.995941
Mean value of the hydrostatic refractivity: 108.111435
======Weather Model class object=====
Weather model time: 2022-02-13 21:00:00
Latitude resolution: 0.25
Longitude resolution: 0.3125
Native projection: EPSG:4326
ZMIN: -100.0
ZMAX: 15000.0
k1 = 0.776
k2 = 0.233
k3 = 3750.0
Humidity type = q
=====================================
Class name: gmao
Dataset: gmao
=====================================
A: []
B: []
Number of points in Lon/Lat = 20/23
Total number of grid points (3D): 66700
=====================================
Weather model GMAO is available from 2014-02-20 00:00:00-Present
Number of weather model nodes: 66700
Shape of weather model: (20, 23, 145)
Bounds of the weather model: 33.50/38.25/-80.31/-73.44 (SNWE)
Weather model: GMAO
Mean value of the wet refractivity: 9.644919
Mean value of the hydrostatic refractivity: 108.516708
======Weather Model class object=====
Weather model time: 2022-02-14 00:00:00
Latitude resolution: 0.25
Longitude resolution: 0.3125
Native projection: EPSG:4326
ZMIN: -100.0
ZMAX: 15000.0
k1 = 0.776
k2 = 0.233
k3 = 3750.0
Humidity type = q
=====================================
Class name: gmao
Dataset: gmao
=====================================
A: []
B: []
Number of points in Lon/Lat = 20/23
Total number of grid points (3D): 66700
=====================================
ERROR:root:Time interpolation weights do not sum to one, something is off with the dates
Traceback (most recent call last):
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/raider.py", line 259, in calcDelays
    assert np.sum(wgts)==1
AssertionError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/conda/envs/RAiDER/bin/raider.py", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/__main__.py", line 29, in main
    process_entry_point.load()()
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/raider.py", line 486, in calcDelaysGUNW
    cube_filenames = calcDelays([path_cfg])
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/raider.py", line 262, in calcDelays
    raise ValueError('Time interpolation weights do not sum to one, something is off with the dates')
ValueError: Time interpolation weights do not sum to one, something is off with the dates
```

Here are all the jobs:

```
[{'job_id': '315abcd3-c22e-4833-b526-0634cfad8a0e',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:34:20+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Norfolk_4_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 493,
   'granules': ['S1A_IW_SLC__1SDV_20220225T230606_20220225T230634_042076_050335_CE69',
    'S1A_IW_SLC__1SDV_20220225T230632_20220225T230659_042076_050335_3D61'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220213T230606_20220213T230634_041901_04FD2B_1CEA',
    'S1A_IW_SLC__1SDV_20220213T230632_20220213T230659_041901_04FD2B_8DB4'],
   'weather_model': 'GMAO'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/315abcd3-c22e-4833-b526-0634cfad8a0e/315abcd3-c22e-4833-b526-0634cfad8a0e.log'],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7513.079, 31.619]},
 {'job_id': '883a9e4a-de24-4670-9215-350cca7ca0e9',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:34:20+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Norfolk_4_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 493,
   'granules': ['S1A_IW_SLC__1SDV_20220225T230606_20220225T230634_042076_050335_CE69',
    'S1A_IW_SLC__1SDV_20220225T230632_20220225T230659_042076_050335_3D61'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220201T230606_20220201T230634_041726_04F710_A081',
    'S1A_IW_SLC__1SDV_20220201T230632_20220201T230659_041726_04F710_3CC9'],
   'weather_model': 'GMAO'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/883a9e4a-de24-4670-9215-350cca7ca0e9/883a9e4a-de24-4670-9215-350cca7ca0e9.log'],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7542.655, 30.971]},
 {'job_id': 'c39d07db-5617-4967-bbf2-76aea1e8c710',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:34:20+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Norfolk_4_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 493,
   'granules': ['S1A_IW_SLC__1SDV_20220213T230606_20220213T230634_041901_04FD2B_1CEA',
    'S1A_IW_SLC__1SDV_20220213T230632_20220213T230659_041901_04FD2B_8DB4'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220120T230607_20220120T230635_041551_04F112_7821',
    'S1A_IW_SLC__1SDV_20220120T230632_20220120T230659_041551_04F112_F3A1'],
   'weather_model': 'GMAO'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/c39d07db-5617-4967-bbf2-76aea1e8c710/c39d07db-5617-4967-bbf2-76aea1e8c710.log'],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7458.485, 31.915]},
 {'job_id': '2985e764-669a-41cd-98cb-d04a29c0afad',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:34:20+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Norfolk_4_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 493,
   'granules': ['S1A_IW_SLC__1SDV_20220213T230606_20220213T230634_041901_04FD2B_1CEA',
    'S1A_IW_SLC__1SDV_20220213T230632_20220213T230659_041901_04FD2B_8DB4'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220201T230606_20220201T230634_041726_04F710_A081',
    'S1A_IW_SLC__1SDV_20220201T230632_20220201T230659_041726_04F710_3CC9'],
   'weather_model': 'GMAO'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/2985e764-669a-41cd-98cb-d04a29c0afad/2985e764-669a-41cd-98cb-d04a29c0afad.log'],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7554.299, 31.529]}]
```

Interestingly, some of the jobs succeed. Here are those that did:

```
[{'job_id': 'd632fa12-9203-4002-ac50-0416aebceaf6',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:34:20+00:00',
  'status_code': 'SUCCEEDED',
  'user_id': 'cmarshak',
  'name': 'Norfolk_4_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 494,
   'granules': ['S1A_IW_SLC__1SDV_20220201T230632_20220201T230659_041726_04F710_3CC9',
    'S1A_IW_SLC__1SDV_20220201T230657_20220201T230724_041726_04F710_9718'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220120T230632_20220120T230659_041551_04F112_F3A1',
    'S1A_IW_SLC__1SDV_20220120T230657_20220120T230724_041551_04F112_DAA7'],
   'weather_model': 'GMAO'},
  'files': [{'filename': 'S1-GUNW-A-R-004-tops-20220201_20220120-230658-00079W_00036N-PP-8150-v2_0_6.nc',
    's3': {'bucket': 'hyp3-a19-jpl-contentbucket-1wfnatpznlg8b',
     'key': 'd632fa12-9203-4002-ac50-0416aebceaf6/S1-GUNW-A-R-004-tops-20220201_20220120-230658-00079W_00036N-PP-8150-v2_0_6.nc'},
    'size': 62581815,
    'url': 'https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/d632fa12-9203-4002-ac50-0416aebceaf6/S1-GUNW-A-R-004-tops-20220201_20220120-230658-00079W_00036N-PP-8150-v2_0_6.nc'}],
  'logs': [],
  'browse_images': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/d632fa12-9203-4002-ac50-0416aebceaf6/S1-GUNW-A-R-004-tops-20220201_20220120-230658-00079W_00036N-PP-8150-v2_0_6.png'],
  'thumbnail_images': [],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7475.834, 89.999]},
 {'job_id': '82b68a0f-3108-4844-8bb3-62da6c794122',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:34:20+00:00',
  'status_code': 'SUCCEEDED',
  'user_id': 'cmarshak',
  'name': 'Norfolk_4_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 492,
   'granules': ['S1A_IW_SLC__1SDV_20220213T230541_20220213T230608_041901_04FD2B_FE0C',
    'S1A_IW_SLC__1SDV_20220213T230606_20220213T230634_041901_04FD2B_1CEA'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220120T230542_20220120T230609_041551_04F112_375E',
    'S1A_IW_SLC__1SDV_20220120T230607_20220120T230635_041551_04F112_7821'],
   'weather_model': 'GMAO'},
  'files': [{'filename': 'S1-GUNW-A-R-004-tops-20220213_20220120-230607-00078W_00034N-PP-ae25-v2_0_6.nc',
    's3': {'bucket': 'hyp3-a19-jpl-contentbucket-1wfnatpznlg8b',
     'key': '82b68a0f-3108-4844-8bb3-62da6c794122/S1-GUNW-A-R-004-tops-20220213_20220120-230607-00078W_00034N-PP-ae25-v2_0_6.nc'},
    'size': 59758979,
    'url': 'https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/82b68a0f-3108-4844-8bb3-62da6c794122/S1-GUNW-A-R-004-tops-20220213_20220120-230607-00078W_00034N-PP-ae25-v2_0_6.nc'}],
  'logs': [],
  'browse_images': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/82b68a0f-3108-4844-8bb3-62da6c794122/S1-GUNW-A-R-004-tops-20220213_20220120-230607-00078W_00034N-PP-ae25-v2_0_6.png'],
  'thumbnail_images': [],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7194.046, 113.277]},
 {'job_id': '634a1d06-e598-4523-a1cc-d64de920b2c1',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:34:20+00:00',
  'status_code': 'SUCCEEDED',
  'user_id': 'cmarshak',
  'name': 'Norfolk_4_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 494,
   'granules': ['S1A_IW_SLC__1SDV_20220225T230632_20220225T230659_042076_050335_3D61',
    'S1A_IW_SLC__1SDV_20220225T230657_20220225T230724_042076_050335_2BA9'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220213T230632_20220213T230659_041901_04FD2B_8DB4',
    'S1A_IW_SLC__1SDV_20220213T230657_20220213T230724_041901_04FD2B_D256'],
   'weather_model': 'GMAO'},
  'files': [{'filename': 'S1-GUNW-A-R-004-tops-20220225_20220213-230658-00079W_00036N-PP-0bbb-v2_0_6.nc',
    's3': {'bucket': 'hyp3-a19-jpl-contentbucket-1wfnatpznlg8b',
     'key': '634a1d06-e598-4523-a1cc-d64de920b2c1/S1-GUNW-A-R-004-tops-20220225_20220213-230658-00079W_00036N-PP-0bbb-v2_0_6.nc'},
    'size': 60295194,
    'url': 'https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/634a1d06-e598-4523-a1cc-d64de920b2c1/S1-GUNW-A-R-004-tops-20220225_20220213-230658-00079W_00036N-PP-0bbb-v2_0_6.nc'}],
  'logs': [],
  'browse_images': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/634a1d06-e598-4523-a1cc-d64de920b2c1/S1-GUNW-A-R-004-tops-20220225_20220213-230658-00079W_00036N-PP-0bbb-v2_0_6.png'],
  'thumbnail_images': [],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7535.166, 89.429]},
 {'job_id': '861fe65c-802f-4ae1-90fb-7c7dbafe65f8',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:34:20+00:00',
  'status_code': 'SUCCEEDED',
  'user_id': 'cmarshak',
  'name': 'Norfolk_4_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 492,
   'granules': ['S1A_IW_SLC__1SDV_20220213T230541_20220213T230608_041901_04FD2B_FE0C',
    'S1A_IW_SLC__1SDV_20220213T230606_20220213T230634_041901_04FD2B_1CEA'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220201T230541_20220201T230608_041726_04F710_1434',
    'S1A_IW_SLC__1SDV_20220201T230606_20220201T230634_041726_04F710_A081'],
   'weather_model': 'GMAO'},
  'files': [{'filename': 'S1-GUNW-A-R-004-tops-20220213_20220201-230607-00078W_00034N-PP-4e09-v2_0_6.nc',
    's3': {'bucket': 'hyp3-a19-jpl-contentbucket-1wfnatpznlg8b',
     'key': '861fe65c-802f-4ae1-90fb-7c7dbafe65f8/S1-GUNW-A-R-004-tops-20220213_20220201-230607-00078W_00034N-PP-4e09-v2_0_6.nc'},
    'size': 59195856,
    'url': 'https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/861fe65c-802f-4ae1-90fb-7c7dbafe65f8/S1-GUNW-A-R-004-tops-20220213_20220201-230607-00078W_00034N-PP-4e09-v2_0_6.nc'}],
  'logs': [],
  'browse_images': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/861fe65c-802f-4ae1-90fb-7c7dbafe65f8/S1-GUNW-A-R-004-tops-20220213_20220201-230607-00078W_00034N-PP-4e09-v2_0_6.png'],
  'thumbnail_images': [],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7297.611, 103.631]},
 {'job_id': 'c4692eba-f013-4395-9321-1ee243e98da4',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:34:20+00:00',
  'status_code': 'SUCCEEDED',
  'user_id': 'cmarshak',
  'name': 'Norfolk_4_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 492,
   'granules': ['S1A_IW_SLC__1SDV_20220201T230541_20220201T230608_041726_04F710_1434',
    'S1A_IW_SLC__1SDV_20220201T230606_20220201T230634_041726_04F710_A081'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220120T230542_20220120T230609_041551_04F112_375E',
    'S1A_IW_SLC__1SDV_20220120T230607_20220120T230635_041551_04F112_7821'],
   'weather_model': 'GMAO'},
  'files': [{'filename': 'S1-GUNW-A-R-004-tops-20220201_20220120-230607-00078W_00034N-PP-7ef9-v2_0_6.nc',
    's3': {'bucket': 'hyp3-a19-jpl-contentbucket-1wfnatpznlg8b',
     'key': 'c4692eba-f013-4395-9321-1ee243e98da4/S1-GUNW-A-R-004-tops-20220201_20220120-230607-00078W_00034N-PP-7ef9-v2_0_6.nc'},
    'size': 58536678,
    'url': 'https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/c4692eba-f013-4395-9321-1ee243e98da4/S1-GUNW-A-R-004-tops-20220201_20220120-230607-00078W_00034N-PP-7ef9-v2_0_6.nc'}],
  'logs': [],
  'browse_images': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/c4692eba-f013-4395-9321-1ee243e98da4/S1-GUNW-A-R-004-tops-20220201_20220120-230607-00078W_00034N-PP-7ef9-v2_0_6.png'],
  'thumbnail_images': [],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7204.255, 240.253]},
 {'job_id': '8c57e80b-ce6f-4846-a5d1-bf48c00950d9',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:34:20+00:00',
  'status_code': 'SUCCEEDED',
  'user_id': 'cmarshak',
  'name': 'Norfolk_4_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 492,
   'granules': ['S1A_IW_SLC__1SDV_20220225T230541_20220225T230608_042076_050335_D763',
    'S1A_IW_SLC__1SDV_20220225T230606_20220225T230634_042076_050335_CE69'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220201T230541_20220201T230608_041726_04F710_1434',
    'S1A_IW_SLC__1SDV_20220201T230606_20220201T230634_041726_04F710_A081'],
   'weather_model': 'GMAO'},
  'files': [{'filename': 'S1-GUNW-A-R-004-tops-20220225_20220201-230607-00078W_00034N-PP-997c-v2_0_6.nc',
    's3': {'bucket': 'hyp3-a19-jpl-contentbucket-1wfnatpznlg8b',
     'key': '8c57e80b-ce6f-4846-a5d1-bf48c00950d9/S1-GUNW-A-R-004-tops-20220225_20220201-230607-00078W_00034N-PP-997c-v2_0_6.nc'},
    'size': 59201395,
    'url': 'https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/8c57e80b-ce6f-4846-a5d1-bf48c00950d9/S1-GUNW-A-R-004-tops-20220225_20220201-230607-00078W_00034N-PP-997c-v2_0_6.nc'}],
  'logs': [],
  'browse_images': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/8c57e80b-ce6f-4846-a5d1-bf48c00950d9/S1-GUNW-A-R-004-tops-20220225_20220201-230607-00078W_00034N-PP-997c-v2_0_6.png'],
  'thumbnail_images': [],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7245.845, 97.055]}]
```

**Comment by cmarshak** [comment]
Here are some additional jobs that failed with the same issue over Hawaii.

```
[{'job_id': '5e9b415e-5a78-42db-94fb-5889a0cc1952',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:39:49+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii-1_87_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 13488,
   'granules': ['S1A_IW_SLC__1SDV_20220126T161601_20220126T161629_041634_04F3F8_AD93',
    'S1A_IW_SLC__1SDV_20220126T161627_20220126T161654_041634_04F3F8_8688'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220114T161602_20220114T161630_041459_04EDFD_896D',
    'S1A_IW_SLC__1SDV_20220114T161628_20220114T161654_041459_04EDFD_99B8'],
   'weather_model': 'GMAO'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/5e9b415e-5a78-42db-94fb-5889a0cc1952/5e9b415e-5a78-42db-94fb-5889a0cc1952.log'],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7069.605, 31.643]},
 {'job_id': 'c707f91f-c2fc-457f-b1ca-9ade8645bf94',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-03-17T18:39:49+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Hawaii-1_87_GMAO_0317',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 13488,
   'granules': ['S1A_IW_SLC__1SDV_20220207T161601_20220207T161629_041809_04F9F7_4C83',
    'S1A_IW_SLC__1SDV_20220207T161627_20220207T161653_041809_04F9F7_52C6'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220114T161602_20220114T161630_041459_04EDFD_896D',
    'S1A_IW_SLC__1SDV_20220114T161628_20220114T161654_041459_04EDFD_99B8'],
   'weather_model': 'GMAO'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/c707f91f-c2fc-457f-b1ca-9ade8645bf94/c707f91f-c2fc-457f-b1ca-9ade8645bf94.log'],
  'expiration_time': '2023-09-14T00:00:00+00:00',
  'processing_times': [7208.646, 31.418]}]
```

**Comment by bbuzz31** [comment]
This is a numerical issue in the line `np.sum(wgts) == 1`

I checked two GUNWs (one Norfolk, one Hawaii), and the sum of `wgts` is 0.9999999999999999.

This isn't == 1, so I've replaced it with `np.iclose(np.sum(wgts), 1)` which will correctly return True.

Fixed in #504

**Comment by dbekaert** [comment]
@cmarshak Once you confirm this issue is removed could you close ticket?

**Comment by cmarshak** [comment]
It's most efficient if @bbuzz31 closes the ticket. He has the GUNW data (he downloaded them and any will do) and can rerun the latest fixes locally. I will rerun hyp3 after.

**Comment by cmarshak** [comment]
And now that I think of it - is there a way you can add a test of some sort in the test suite to make sure this is correct going forward?
