### ISSUE TITLE
[BUG] No weather model successfully obtained for HRES

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#554]
**Describe the bug**

Related to jobs submitted in #552 - some jobs errored out very quickly. I checked the logs and these jobs have a different message.

```
Downloading s3://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b/2cf027ba-03e5-4e94-a11d-728a8263d396/S1-GUNW-D-R-048-tops-20220228_20220204-235927-00090E_00041N-PP-ee03-v3_0_0.nc to S1-GUNW-D-R-048-tops-20220228_20220204-235927-00090E_00041N-PP-ee03-v3_0_0.nc
Downloading s3://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b/2cf027ba-03e5-4e94-a11d-728a8263d396/S1-GUNW-D-R-048-tops-20220228_20220204-235927-00090E_00041N-PP-ee03-v3_0_0.json to S1-GUNW-D-R-048-tops-20220228_20220204-235927-00090E_00041N-PP-ee03-v3_0_0.json
Writing /home/raider/.ecmwfapirc locally!

Downloading products:   0%|          | 0/1 [00:00<?, ?product/s]

Downloading S1A_OPER_AUX_POEORB_OPOD_20220321T081256_V20220228T225942_20220302T005942.EOF:   0%|          | 0.00/4.41M [00:00<?, ?B/s][A

Downloading S1A_OPER_AUX_POEORB_OPOD_20220321T081256_V20220228T225942_20220302T005942.EOF:  24%|â–ˆâ–ˆâ–       | 1.05M/4.41M [00:00<00:03, 1.07MB/s][A

Downloading S1A_OPER_AUX_POEORB_OPOD_20220321T081256_V20220228T225942_20220302T005942.EOF:  48%|â–ˆâ–ˆâ–ˆâ–ˆâ–Š     | 2.10M/4.41M [00:01<00:01, 2.10MB/s][A

Downloading S1A_OPER_AUX_POEORB_OPOD_20220321T081256_V20220228T225942_20220302T005942.EOF:  95%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ| 4.19M/4.41M [00:01<00:00, 4.42MB/s][A
Downloading S1A_OPER_AUX_POEORB_OPOD_20220321T081256_V20220228T225942_20220302T005942.EOF: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4.41M/4.41M [00:01<00:00, 3.37MB/s]

MD5 checksumming:   0%|          | 0.00/4.41M [00:00<?, ?B/s][A

                                                             [A
Downloading products: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:02<00:00,  2.01s/product]
Downloading products: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:02<00:00,  2.01s/product]
Wrote new cfg file: GUNW_20220228-20220204_235927.yaml
[33;21mWARNING: Weather model only extends to the surface topography; height levels below the topography will be interpolated from the surface and may be inaccurate.[0m
Invalid extension GTiff for cube. Defaulting to .nc
Invalid extension GTiff for cube. Defaulting to .nc
Output cube spacing: 0.1 degrees
Output SNWE: [41.0, 43.1, 89.9, 93.8]
Starting to run the weather model calculation
Date: 20220228
Beginning weather model pre-processing
Weather model HRES is available from 1983-04-20 to Present
2023-06-16 03:25:43 ECMWF API python library 1.6.3
2023-06-16 03:25:43 ECMWF API at https://api.ecmwf.int/v1
2023-06-16 03:25:44 Welcome David Bekaert
2023-06-16 03:25:45 In case of problems, please check https://confluence.ecmwf.int/display/WEBAPI/Web+API+FAQ or contact servicedesk@ecmwf.int
2023-06-16 03:25:46 Request submitted
2023-06-16 03:25:46 Request id: 648bd63ac81ad61ffe9e7ef0
2023-06-16 03:25:46 Request is submitted
[31;21mERROR: 'ecmwf.API error 1: ERROR 102 (USER_QUEUED_LIMIT_EXCEEDED): Too many queued requests. Max allowed queued requests per user is 20.'[0m
Weather model point bounds are 41.00/43.10/89.90/94.43
Query datetime: 2022-03-01 00:00:00
[31;21mERROR: [Errno 2] No such file or directory: '/home/raider/weather_files/HRES_2022_03_01_T00_00_00.nc'[0m
[31;21mERROR: Downloading and/or preparation of HRES failed.[0m
[31;21mERROR: No weather model data was successfully obtained.[0m
Traceback (most recent call last):
  File "/opt/conda/envs/RAiDER/bin/raider.py", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/__main__.py", line 42, in main
    process_entry_point.load()()
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/raider.py", line 523, in calcDelaysGUNW
    cube_filenames = calcDelays([path_cfg])
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/raider.py", line 276, in calcDelays
    raise RuntimeError
RuntimeError
```

Here are some of the relevant jobs:

```
{'job_id': '2cf027ba-03e5-4e94-a11d-728a8263d396',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-06-16T01:00:47+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Tibet_48_HRES_0615',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 7419,
   'granules': ['S1A_IW_SLC__1SDV_20220228T235901_20220228T235929_042120_0504AF_6899',
    'S1A_IW_SLC__1SDV_20220228T235927_20220228T235954_042120_0504AF_0D7B'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220204T235901_20220204T235929_041770_04F88B_F6CE',
    'S1A_IW_SLC__1SDV_20220204T235927_20220204T235954_041770_04F88B_BD1D'],
   'weather_model': 'HRES'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/2cf027ba-03e5-4e94-a11d-728a8263d396/2cf027ba-03e5-4e94-a11d-728a8263d396.log'],
  'expiration_time': '2023-12-14T00:00:00+00:00',
  'processing_times': [7450.047, 13.444]},
 {'job_id': 'b3d5e3b9-30ad-402b-ba32-29d169502809',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-06-16T01:00:47+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Tibet_48_HRES_0615',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 7420,
   'granules': ['S1A_IW_SLC__1SDV_20220216T235927_20220216T235954_041945_04FEB2_5555',
    'S1A_IW_SLC__1SDV_20220216T235952_20220217T000019_041945_04FEB2_BE03'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220123T235928_20220123T235955_041595_04F294_3E01',
    'S1A_IW_SLC__1SDV_20220123T235953_20220124T000020_041595_04F294_C407'],
   'weather_model': 'HRES'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/b3d5e3b9-30ad-402b-ba32-29d169502809/b3d5e3b9-30ad-402b-ba32-29d169502809.log'],
  'expiration_time': '2023-12-14T00:00:00+00:00',
  'processing_times': [7607.973, 13.85]}
```

**Comment by cmarshak** [comment]
Hmmm...

It's still using `David Bekaert` - I am not sure why.


```
2023-06-16 03:25:44 Welcome David Bekaert
```

It should say `Welcome NASA Jet`. I am confused as I changed the secrets to the new account in AWS. What am I doing wrong here?

@asjohnston-asf
