### ISSUE TITLE
[BUG] Hyp3 GUNW id not extracted as Expected

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#596]
After #593, we look at the GUNW id here to avoid processing tropo delays when HRRR is not available: https://github.com/dbekaert/RAiDER/blob/dev/tools/RAiDER/cli/raider.py#L611-L618

To do so, we break apart the tokens in these two functions of the GUNW id, where this error is being raised: https://github.com/dbekaert/RAiDER/blob/dev/tools/RAiDER/aria/prepFromGUNW.py#L34-L73

Clearly, the bucket prefix is not getting read correctly. Or maybe I am not aware of the control flow here properly in the cloud.

Here is the input dict:

```
{'job_id': '9023f2fe-991d-4e8d-af73-4e8862ee11dd',
 'job_type': 'INSAR_ISCE_TEST',
 'request_time': '2023-09-21T21:04:18+00:00',
 'status_code': 'FAILED',
 'user_id': 'cmarshak',
 'name': 'issue_587',
 'job_parameters': {'compute_solid_earth_tide': True,
  'estimate_ionosphere_delay': True,
  'frame_id': 7348,
  'granules': ['S1A_IW_SLC__1SDV_20171203T233018_20171203T233045_019545_0212EB_54DF',
   'S1A_IW_SLC__1SDV_20171203T233043_20171203T233110_019545_0212EB_4821'],
  'secondary_granules': ['S1A_IW_SLC__1SDV_20161126T233013_20161126T233041_014120_016CA2_B4C8',
   'S1A_IW_SLC__1SDV_20161126T233039_20161126T233106_014120_016CA2_D9AD'],
  'weather_model': 'HRRR'},
 'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/9023f2fe-991d-4e8d-af73-4e8862ee11dd/9023f2fe-991d-4e8d-af73-4e8862ee11dd.log'],
 'expiration_time': '2024-03-20T00:00:00+00:00',
 'processing_times': [10065.542, 4.543]}
```
and here is the resulting log:

```
 â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
 â”‚ I'm building Herbie's default config file.      â”‚
 â•°â•¥â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
 ðŸ‘·ðŸ»â€â™‚ï¸
 â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
 â”‚ You're ready to go.                             â”‚
 â”‚ You may edit the config file here:              â”‚
 â”‚ /home/raider/.config/herbie/config.toml         â”‚
 â•°â•¥â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
 ðŸ‘·ðŸ»â€â™‚ï¸
/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/__main__.py:36: DeprecationWarning: Accessing entry points by index is deprecated. Cast to tuple if needed.
  process_entry_point = entry_points(group='console_scripts', name=f'{args.process}.py')[0]
Traceback (most recent call last):
  File "/opt/conda/envs/RAiDER/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/RAiDER/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/__main__.py", line 46, in <module>
    main()
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/__main__.py", line 42, in main
    process_entry_point.load()()
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/cli/raider.py", line 616, in calcDelaysGUNW
    if not RAiDER.aria.prepFromGUNW.check_hrrr_dataset_availablity_for_s1_azimuth_time_interpolation(gunw_id):
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/aria/prepFromGUNW.py", line 64, in check_hrrr_dataset_availablity_for_s1_azimuth_time_interpolation
    ref_acq_time = _get_acq_time_from_gunw_id(gunw_id, 'reference')
  File "/opt/conda/envs/RAiDER/lib/python3.10/site-packages/RAiDER/aria/prepFromGUNW.py", line 39, in _get_acq_time_from_gunw_id
    date_tokens = tokens[6].split('_')
IndexError: list index out of range
```

Clearly, finding the GUNW id using builtin string logic is failing. I am confused because I do not know how hyp3 is passing in the bucket/bucket prefix here.

Locally, I am succeeding in that I can use the url for the GUNW in the specified job here: https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/9023f2fe-991d-4e8d-af73-4e8862ee11dd/S1-GUNW-A-R-048-tops-20171203_20161126-233044-00084W_00035N-PP-7fef-v3_0_0.nc

and locally get what I expect. It's clearly a basic string parse that I can't quite follow through on. I am sorry to ask you about this.

Locally, I get:

```
raider.py ++process calcDelaysGUNW --bucket s3://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b --bucket-prefix 9023f2fe-991d-4e8d-af73-4e8862ee11dd/S1-GUNW-A-R-048-tops-20171203_20161126-233044-00084W_00035N-PP-7fef-v3_0_0.nc -m HRRR -interp azimuth_time_grid -m HRRR -interp azimuth_time_grid
```

```
✅ Found ┊ model=hrrr ┊ product=nat ┊ 2017-Dec-04 00:00 UTC F00 ┊ GRIB2 @ aws ┊ IDX @ aws
✅ Found ┊ model=hrrr ┊ product=nat ┊ 2017-Dec-03 23:00 UTC F00 ┊ GRIB2 @ aws ┊ IDX @ aws
💔 Did not find ┊ model=hrrr ┊ product=nat ┊ 2016-Nov-27 00:00 UTC F00
💔 Did not find ┊ model=hrrr ┊ product=nat ┊ 2016-Nov-26 23:00 UTC F00
The required HRRR data for time-grid interpolation is not available; returning None and not modifying GUNW dataset
```
I know this is a simple fix, but I would rather not have to redo this piece of code to download GUNW and read the slc ids (as is done in latter parts of the code). If @asjohnston-asf and/or @jhkennedy can point me how this is actually getting called so I can fix this error without putting a print statement in the dev branch 🤦.

Thanks in advance for your help!

**Comment by cmarshak** [comment]
I am able to answer my own question... you really need to download the products first... I see how the data is passed looking at the step functions:

```
["++process","calcDelaysGUNW","--bucket","hyp3-a19-jpl-contentbucket-1wfnatpznlg8b","--bucket-prefix","9023f2fe-991d-4e8d-af73-4e8862ee11dd","--weather-model","HRRR"]
```

GUNW is not in the prefix. I will fix this and update the tests accordingly.
