### ISSUE TITLE
[BUG] ~/.netrc access too permissive: access permissions must restrict access to only the owner

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#617]
Here is a sample log:

```
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
 â”‚ I'm building Herbie's default config file.      â”‚
 â•°â•¥â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
 ðŸ‘·ðŸ»â€â™‚ï¸
 â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
 â”‚ You're ready to go.                             â”‚
 â”‚ You may edit the config file here:              â”‚
 â”‚ /home/raider/.config/herbie/config.toml         â”‚
 â•°â•¥â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
 ðŸ‘·ðŸ»â€â™‚ï¸
Downloading s3://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b/98d7a79e-69a1-4234-8203-ac76c37579a8/S1-GUNW-A-R-064-tops-20220206_20220125-015020-00119W_00032N-PP-b0e2-v3_0_0.nc to S1-GUNW-A-R-064-tops-20220206_20220125-015020-00119W_00032N-PP-b0e2-v3_0_0.nc
âœ… Found â”Š model=hrrr â”Š [3mproduct=nat[0m â”Š [38;2;41;130;13m2022-Feb-06 02:00 UTC[92m F00[0m â”Š [38;2;255;153;0m[3mGRIB2 @ aws[0m â”Š [38;2;255;153;0m[3mIDX @ aws[0m
âœ… Found â”Š model=hrrr â”Š [3mproduct=nat[0m â”Š [38;2;41;130;13m2022-Feb-06 01:00 UTC[92m F00[0m â”Š [38;2;255;153;0m[3mGRIB2 @ aws[0m â”Š [38;2;255;153;0m[3mIDX @ aws[0m
âœ… Found â”Š model=hrrr â”Š [3mproduct=nat[0m â”Š [38;2;41;130;13m2022-Jan-25 02:00 UTC[92m F00[0m â”Š [38;2;255;153;0m[3mGRIB2 @ aws[0m â”Š [38;2;255;153;0m[3mIDX @ aws[0m
âœ… Found â”Š model=hrrr â”Š [3mproduct=nat[0m â”Š [38;2;41;130;13m2022-Jan-25 01:00 UTC[92m F00[0m â”Š [38;2;255;153;0m[3mGRIB2 @ aws[0m â”Š [38;2;255;153;0m[3mIDX @ aws[0m
/opt/conda/envs/RAiDER/lib/python3.12/site-packages/xarray/backends/plugins.py:80: RuntimeWarning: Engine 'gini' loading failed:
Struct() takes at most 1 argument (3 given)
  warnings.warn(f"Engine {name!r} loading failed:\n{ex}", RuntimeWarning)
Downloading s3://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b/98d7a79e-69a1-4234-8203-ac76c37579a8/S1-GUNW-A-R-064-tops-20220206_20220125-015020-00119W_00032N-PP-b0e2-v3_0_0.json to S1-GUNW-A-R-064-tops-20220206_20220125-015020-00119W_00032N-PP-b0e2-v3_0_0.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/cli/__main__.py", line 44, in <module>
    main()
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/cli/__main__.py", line 40, in main
    process_entry_point.load()()
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/cli/raider.py", line 548, in calcDelaysGUNW
    path_cfg, wavelength = RAiDER.aria.prepFromGUNW.main(iargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/aria/prepFromGUNW.py", line 400, in main
    GUNWObj = GUNW(args.file, args.weather_model, args.output_directory)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/aria/prepFromGUNW.py", line 165, in __post_init__
    self.OrbitFile  = self.get_orbit_file()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/aria/prepFromGUNW.py", line 280, in get_orbit_file
    path_orb = eof.download.download_eofs([dt], [sat], save_dir=orbit_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/eof/download.py", line 92, in download_eofs
    client = DataspaceClient(username=cdse_user, password=cdse_password)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/eof/dataspace_client.py", line 38, in __init__
    username, password = get_netrc_credentials(DATASPACE_HOST)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/eof/_auth.py", line 89, in get_netrc_credentials
    n = netrc.netrc()
        ^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/netrc.py", line 75, in __init__
    self._parse(file, fp, default_netrc)
  File "/opt/conda/envs/RAiDER/lib/python3.12/netrc.py", line 142, in _parse
    self._security_check(fp, default_netrc, self.hosts[entryname][0])
  File "/opt/conda/envs/RAiDER/lib/python3.12/netrc.py", line 161, in _security_check
    raise NetrcParseError(
netrc.NetrcParseError: ~/.netrc access too permissive: access permissions must restrict access to only the owner (None, line None)
```

Looks like these are all failing at Raider step; sample jobs over LA:

```
[{'job_id': '98d7a79e-69a1-4234-8203-ac76c37579a8',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9847,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/98d7a79e-69a1-4234-8203-ac76c37579a8/98d7a79e-69a1-4234-8203-ac76c37579a8.log'],
  'expiration_time': '2024-05-21T00:00:00+00:00',
  'processing_times': [6889.867, 8.739]},
 {'job_id': 'abc7c403-22d3-470c-899b-41d6e2524f90',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'RUNNING',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9848,
   'granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A',
    'S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015007_20220113T015037_041436_04ED43_1441',
    'S1A_IW_SLC__1SDV_20220113T015034_20220113T015102_041436_04ED43_9F80'],
   'weather_model': 'HRRR'}},
 {'job_id': '8668c753-c731-40b8-987d-92d7d9658002',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9847,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015005_20220218T015035_041961_04FF34_65A4'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/8668c753-c731-40b8-987d-92d7d9658002/8668c753-c731-40b8-987d-92d7d9658002.log'],
  'expiration_time': '2024-05-21T00:00:00+00:00',
  'processing_times': [5517.819, 7.999]},
 {'job_id': 'd95373f0-90f7-4134-a824-2565fde4c237',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'RUNNING',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9849,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C',
    'S1A_IW_SLC__1SDV_20220206T015059_20220206T015126_041786_04F91C_5AC7'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805',
    'S1A_IW_SLC__1SDV_20220125T015059_20220125T015126_041611_04F317_8459'],
   'weather_model': 'HRRR'}},
 {'job_id': 'a24b5e36-bce1-4432-90aa-5dc2c3d055ab',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'RUNNING',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9849,
   'granules': ['S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805',
    'S1A_IW_SLC__1SDV_20220125T015059_20220125T015126_041611_04F317_8459'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015034_20220113T015102_041436_04ED43_9F80',
    'S1A_IW_SLC__1SDV_20220113T015100_20220113T015127_041436_04ED43_14E4'],
   'weather_model': 'HRRR'}},
 {'job_id': 'c8b60601-7c4a-4e99-b92d-05902163fb83',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9847,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015005_20220218T015035_041961_04FF34_65A4'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/c8b60601-7c4a-4e99-b92d-05902163fb83/c8b60601-7c4a-4e99-b92d-05902163fb83.log'],
  'expiration_time': '2024-05-21T00:00:00+00:00',
  'processing_times': [5509.174, 8.218]},
 {'job_id': 'a0f016b3-9825-49b1-b4c2-2f481c092dfd',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'RUNNING',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9848,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015005_20220218T015035_041961_04FF34_65A4',
    'S1A_IW_SLC__1SDV_20220218T015033_20220218T015101_041961_04FF34_E691'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A',
    'S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805'],
   'weather_model': 'HRRR'}},
 {'job_id': '6440d7f2-479b-49a3-95c8-2eba5792b26b',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9847,
   'granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015007_20220113T015037_041436_04ED43_1441'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/6440d7f2-479b-49a3-95c8-2eba5792b26b/6440d7f2-479b-49a3-95c8-2eba5792b26b.log'],
  'expiration_time': '2024-05-21T00:00:00+00:00',
  'processing_times': [6850.148, 8.421]},
 {'job_id': 'b470f629-4f12-46e4-ad20-b7c007fc8a3a',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'RUNNING',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9849,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C',
    'S1A_IW_SLC__1SDV_20220206T015059_20220206T015126_041786_04F91C_5AC7'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015034_20220113T015102_041436_04ED43_9F80',
    'S1A_IW_SLC__1SDV_20220113T015100_20220113T015127_041436_04ED43_14E4'],
   'weather_model': 'HRRR'}},
 {'job_id': 'f7158a25-e298-4f63-bf7a-551ce16ad71c',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'RUNNING',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9848,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015005_20220218T015035_041961_04FF34_65A4',
    'S1A_IW_SLC__1SDV_20220218T015033_20220218T015101_041961_04FF34_E691'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC',
    'S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C'],
   'weather_model': 'HRRR'}},
 {'job_id': '8e5ff3f1-8461-4fcb-91cb-9e6a3b84df3c',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'RUNNING',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9849,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015033_20220218T015101_041961_04FF34_E691',
    'S1A_IW_SLC__1SDV_20220218T015059_20220218T015126_041961_04FF34_DD48'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805',
    'S1A_IW_SLC__1SDV_20220125T015059_20220125T015126_041611_04F317_8459'],
   'weather_model': 'HRRR'}},
 {'job_id': '5d68cf6a-3762-44ef-b46e-d43bffe8964f',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9848,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC',
    'S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015007_20220113T015037_041436_04ED43_1441',
    'S1A_IW_SLC__1SDV_20220113T015034_20220113T015102_041436_04ED43_9F80'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/5d68cf6a-3762-44ef-b46e-d43bffe8964f/5d68cf6a-3762-44ef-b46e-d43bffe8964f.log'],
  'expiration_time': '2024-05-21T00:00:00+00:00',
  'processing_times': [8750.294, 8.058]},
 {'job_id': '9bc07b3c-0677-4673-af9b-7a9183022f20',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9847,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015007_20220113T015037_041436_04ED43_1441'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/9bc07b3c-0677-4673-af9b-7a9183022f20/9bc07b3c-0677-4673-af9b-7a9183022f20.log'],
  'expiration_time': '2024-05-21T00:00:00+00:00',
  'processing_times': [6850.175, 8.311]},
 {'job_id': '1437a7dd-1b9c-4314-ae11-27d41ef07cb8',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'RUNNING',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9848,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC',
    'S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A',
    'S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805'],
   'weather_model': 'HRRR'}},
 {'job_id': '36fff253-45c1-4261-b958-7e038c273edd',
  'job_type': 'INSAR_ISCE',
  'request_time': '2023-11-21T22:05:44+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1121',
  'job_parameters': {'compute_solid_earth_tide': True,
   'estimate_ionosphere_delay': True,
   'frame_id': 9849,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015033_20220218T015101_041961_04FF34_E691',
    'S1A_IW_SLC__1SDV_20220218T015059_20220218T015126_041961_04FF34_DD48'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C',
    'S1A_IW_SLC__1SDV_20220206T015059_20220206T015126_041786_04F91C_5AC7'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/36fff253-45c1-4261-b958-7e038c273edd/36fff253-45c1-4261-b958-7e038c273edd.log'],
  'expiration_time': '2024-05-21T00:00:00+00:00',
  'processing_times': [8045.098, 9.241]}]
```

**Comment by jhkennedy** [comment]
I've resubmitted these as `INSAR_ISCE_TEST` jobs to ensure we've correctly fixed the `.netrc` issue; if they all run through, I'll open a release PR to ship it. 

You can get to these jobs like:
```python
import hyp3_sdk as sdk

hyp3 = sdk.HyP3('https://hyp3-a19-jpl.asf.alaska.edu')
jobs = hyp3.find_jobs(name='Los-Angeles-0_64_HRRR_1121', user_id='jhkennedy')
```
