### ISSUE TITLE
[BUG] New Orbit Download is Failing w.r.t. `sentineleof`: `ValueError: missions arg must be same length as orbit_dts`

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#622]
Error log is here:

```
â•­â”€[48;2;255;255;255m[38;2;136;33;27mâ–Œ[0m[38;2;12;53;118m[48;2;240;234;210mâ–Œ[38;2;0;0;0m[1mHerbie[0mâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
 â”‚ INFO: Created a default config file.                 â”‚
 â”‚ You may view/edit Herbie's configuration here:       â”‚
 â”‚ [38;2;255;153;0m     /home/raider/.config/herbie/config.toml      [0m   â”‚
 ....
Weather model: HRRR
Mean value of the wet refractivity: 11.537232
Mean value of the hydrostatic refractivity: 179.089081
======Weather Model class object=====
Weather model time: 2022-02-06 01:00:00
Latitude resolution: 0.02702702702702703
Longitude resolution: 0.02702702702702703
Native projection: PROJCRS["unknown",BASEGEOGCRS["unknown",DATUM["unknown",ELLIPSOID["unknown",6371229,0,LENGTHUNIT["metre",1,ID["EPSG",9001]]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8901]]],CONVERSION["unknown",METHOD["Lambert Conic Conformal (2SP)",ID["EPSG",9802]],PARAMETER["Latitude of false origin",38.5,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8821]],PARAMETER["Longitude of false origin",262.5,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8822]],PARAMETER["Latitude of 1st standard parallel",38.5,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8823]],PARAMETER["Latitude of 2nd standard parallel",38.5,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8824]],PARAMETER["Easting at false origin",0,LENGTHUNIT["metre",1],ID["EPSG",8826]],PARAMETER["Northing at false origin",0,LENGTHUNIT["metre",1],ID["EPSG",8827]]],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]
ZMIN: -100.0
ZMAX: 26000.0
k1 = 0.776
k2 = 0.233
k3 = 3750.0
Humidity type = q
=====================================
Class name: hrrr
Dataset: hrrr
=====================================
A: []
B: []
Number of points in Lon/Lat = 108/140
Total number of grid points (3D): 861840
=====================================
Extent of the weather model is (xmin, ymin, xmax, ymax):-120.14, 31.06, -115.06, 34.67
Extent of the input is (xmin, ymin, xmax, ymax): -118.80, 31.95, -115.70, 33.80
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/cli/__main__.py", line 44, in <module>
    main()
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/cli/__main__.py", line 40, in main
    process_entry_point.load()()
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/cli/raider.py", line 552, in calcDelaysGUNW
    cube_filenames = calcDelays([path_cfg])
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/cli/raider.py", line 305, in calcDelays
    weather_model_file = getWeatherFile(wfiles, times, t, model._Name, interp_method)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/cli/raider.py", line 651, in getWeatherFile
    weather_model_file = combine_weather_files(
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/cli/raider.py", line 689, in combine_weather_files
    time_grid = get_time_grid_for_aztime_interp(datasets, t, model)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/cli/raider.py", line 785, in get_time_grid_for_aztime_interp
    time_grid = get_s1_azimuth_time_grid(lon, lat, hgt, t) # This is the acq time from loop
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/s1_azimuth_timing.py", line 186, in get_s1_azimuth_time_grid
    orb_files = get_orbits_from_slc_ids(slc_ids)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/RAiDER/s1_orbits.py", line 62, in get_orbits_from_slc_ids
    orb_files = eof.download.download_eofs(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/RAiDER/lib/python3.12/site-packages/eof/download.py", line 80, in download_eofs
    raise ValueError("missions arg must be same length as orbit_dts")
ValueError: missions arg must be same length as orbit_dts
```

Here are 15 jobs all of which failed:

```
[{'job_id': 'e71da76c-5081-4119-8a15-f24974b48229',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9847,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/e71da76c-5081-4119-8a15-f24974b48229/e71da76c-5081-4119-8a15-f24974b48229.log'],
  'expiration_time': '2024-06-20T00:00:00+00:00',
  'processing_times': [6679.906, 238.523]},
 {'job_id': 'e4a16103-f8ee-4e35-b503-83b24e73f991',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9847,
   'granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015007_20220113T015037_041436_04ED43_1441'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/e4a16103-f8ee-4e35-b503-83b24e73f991/e4a16103-f8ee-4e35-b503-83b24e73f991.log'],
  'expiration_time': '2024-06-20T00:00:00+00:00',
  'processing_times': [6320.319, 253.377]},
 {'job_id': '54df8b72-4677-497d-ac12-61137493863e',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9848,
   'granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A',
    'S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015007_20220113T015037_041436_04ED43_1441',
    'S1A_IW_SLC__1SDV_20220113T015034_20220113T015102_041436_04ED43_9F80'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/54df8b72-4677-497d-ac12-61137493863e/54df8b72-4677-497d-ac12-61137493863e.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [8510.82, 250.408]},
 {'job_id': 'e8bca9de-7fa0-45be-a9c4-f58710dd09e8',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9849,
   'granules': ['S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805',
    'S1A_IW_SLC__1SDV_20220125T015059_20220125T015126_041611_04F317_8459'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015034_20220113T015102_041436_04ED43_9F80',
    'S1A_IW_SLC__1SDV_20220113T015100_20220113T015127_041436_04ED43_14E4'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/e8bca9de-7fa0-45be-a9c4-f58710dd09e8/e8bca9de-7fa0-45be-a9c4-f58710dd09e8.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [7813.603, 254.282]},
 {'job_id': '10e8f1e0-f7d3-411a-b14f-779dc8d65e3f',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9849,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015033_20220218T015101_041961_04FF34_E691',
    'S1A_IW_SLC__1SDV_20220218T015059_20220218T015126_041961_04FF34_DD48'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C',
    'S1A_IW_SLC__1SDV_20220206T015059_20220206T015126_041786_04F91C_5AC7'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/10e8f1e0-f7d3-411a-b14f-779dc8d65e3f/10e8f1e0-f7d3-411a-b14f-779dc8d65e3f.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [8640.956, 249.254]},
 {'job_id': '3d603851-4a26-43a9-a6a9-b4e88ac2251a',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9847,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015005_20220218T015035_041961_04FF34_65A4'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/3d603851-4a26-43a9-a6a9-b4e88ac2251a/3d603851-4a26-43a9-a6a9-b4e88ac2251a.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [6964.948, 249.941]},
 {'job_id': '2076fa76-3cc0-4a1f-90d8-78607b3419d9',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9848,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC',
    'S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A',
    'S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/2076fa76-3cc0-4a1f-90d8-78607b3419d9/2076fa76-3cc0-4a1f-90d8-78607b3419d9.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [8890.318, 252.144]},
 {'job_id': '70dc9721-f3e0-4ca0-8312-32c057603ddb',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9849,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C',
    'S1A_IW_SLC__1SDV_20220206T015059_20220206T015126_041786_04F91C_5AC7'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015034_20220113T015102_041436_04ED43_9F80',
    'S1A_IW_SLC__1SDV_20220113T015100_20220113T015127_041436_04ED43_14E4'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/70dc9721-f3e0-4ca0-8312-32c057603ddb/70dc9721-f3e0-4ca0-8312-32c057603ddb.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [7811.821, 262.876]},
 {'job_id': 'cdbd0305-2279-4454-a655-f925ab557b0a',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9848,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015005_20220218T015035_041961_04FF34_65A4',
    'S1A_IW_SLC__1SDV_20220218T015033_20220218T015101_041961_04FF34_E691'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015006_20220125T015036_041611_04F317_D09A',
    'S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/cdbd0305-2279-4454-a655-f925ab557b0a/cdbd0305-2279-4454-a655-f925ab557b0a.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [8964.122, 258.21]},
 {'job_id': '87218826-12d8-45ba-b742-a266ed2e8567',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9848,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC',
    'S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015007_20220113T015037_041436_04ED43_1441',
    'S1A_IW_SLC__1SDV_20220113T015034_20220113T015102_041436_04ED43_9F80'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/87218826-12d8-45ba-b742-a266ed2e8567/87218826-12d8-45ba-b742-a266ed2e8567.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [8510.632, 249.852]},
 {'job_id': 'c733fa24-77c5-4900-b343-8aec466a6c89',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9849,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C',
    'S1A_IW_SLC__1SDV_20220206T015059_20220206T015126_041786_04F91C_5AC7'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805',
    'S1A_IW_SLC__1SDV_20220125T015059_20220125T015126_041611_04F317_8459'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/c733fa24-77c5-4900-b343-8aec466a6c89/c733fa24-77c5-4900-b343-8aec466a6c89.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [8584.671, 244.861]},
 {'job_id': 'bed58096-57dc-41f0-b006-01c40d80932e',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9849,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015033_20220218T015101_041961_04FF34_E691',
    'S1A_IW_SLC__1SDV_20220218T015059_20220218T015126_041961_04FF34_DD48'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805',
    'S1A_IW_SLC__1SDV_20220125T015059_20220125T015126_041611_04F317_8459'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/bed58096-57dc-41f0-b006-01c40d80932e/bed58096-57dc-41f0-b006-01c40d80932e.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [8612.024, 234.317]},
 {'job_id': '29f2e769-6b79-44cf-bfd9-c7cdd6546466',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9848,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015005_20220218T015035_041961_04FF34_65A4',
    'S1A_IW_SLC__1SDV_20220218T015033_20220218T015101_041961_04FF34_E691'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC',
    'S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/29f2e769-6b79-44cf-bfd9-c7cdd6546466/29f2e769-6b79-44cf-bfd9-c7cdd6546466.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [8943.869, 242.203]},
 {'job_id': '1cd50c02-3779-438b-ad14-3d6b46c85a2b',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9847,
   'granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220113T015007_20220113T015037_041436_04ED43_1441'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/1cd50c02-3779-438b-ad14-3d6b46c85a2b/1cd50c02-3779-438b-ad14-3d6b46c85a2b.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [6680.785, 243.33]},
 {'job_id': '4685dcc2-37db-4416-9de5-6a88206d8086',
  'job_type': 'INSAR_ISCE_TEST',
  'request_time': '2023-12-22T21:58:15+00:00',
  'status_code': 'FAILED',
  'user_id': 'cmarshak',
  'name': 'Los-Angeles-0_64_HRRR_1222',
  'job_parameters': {'frame_id': 9847,
   'granules': ['S1A_IW_SLC__1SDV_20220218T015005_20220218T015035_041961_04FF34_65A4'],
   'secondary_granules': ['S1A_IW_SLC__1SDV_20220206T015006_20220206T015035_041786_04F91C_FABC'],
   'weather_model': 'HRRR'},
  'logs': ['https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/4685dcc2-37db-4416-9de5-6a88206d8086/4685dcc2-37db-4416-9de5-6a88206d8086.log'],
  'expiration_time': '2024-06-21T00:00:00+00:00',
  'processing_times': [6797.301, 246.509]}]
```

**Comment by scottstanie** [comment]
ah it looks like it's passing a list of 1 mission, but creating two datetime strings per sentinel file when it does this 
```python
In [2]: import re; from pathlib import Path
In [3]: safes = sorted(Path(".").glob("*.SAFE"))
In [4]: slc_ids = [s.name for s in safes]
In [5]: slc_ids
Out[5]:
['S1A_IW_SLC__1SDV_20190708T083419_20190708T083446_028023_032A31_3850.SAFE',
 'S1A_IW_SLC__1SDV_20210416T083427_20210416T083454_037473_046B05_5F0C.SAFE',
 'S1A_IW_SLC__1SDV_20210428T083427_20210428T083454_037648_047116_2170.SAFE',
 'S1A_IW_SLC__1SDV_20230112T083427_20230112T083454_046748_059ABA_08CC.SAFE']

In [6]: missions = {slc_id[0:3] for slc_id in slc_ids}
In [8]: start_times = {re.split(r'_+', slc_id)[4] for slc_id in slc_ids}
In [9]: stop_times = {re.split(r'_+', slc_id)[5] for slc_id in slc_ids}
In [10]: times = sorted(start_times | stop_times)
In [11]: times
Out[11]:
['20190708T083419',
 '20190708T083446',
 '20210416T083427',
 '20210416T083454',
 '20210428T083427',
 '20210428T083454',
 '20230112T083427',
 '20230112T083454']

In [12]: list(missions)
Out[12]: ['S1A']
```

I do find the way i set up the requested inputs a little strange (two lists of equal length), but I think I was imagining it mostly coming from some list of sentinel files.

not sure what the exact best outcome is, but you could do something like 
```python
In [21]: from itertools import product
In [22]: list(product(times, missions))
In [23]: time_tuple, mission_tuple = zip(*list(product(times, missions)))

In [24]: mission_tuple
Out[24]: ('S1A', 'S1A', 'S1A', 'S1A', 'S1A', 'S1A', 'S1A', 'S1A')

In [25]: time_tuple
Out[25]:
('20190708T083419',
 '20190708T083446',
 '20210416T083427',
 '20210416T083454',
 '20210428T083427',
 '20210428T083454',
 '20230112T083427',
 '20230112T083454')
```

**Comment by cmarshak** [comment]
Thanks, @scottstanie, for your help - will try to fix this next week.
